http:
  debug_endpoints: true

input:
  oracledb_cdc:
    # connection_string: oracle://testdb:testdb123@localhost:1521/TESTPDB
    connection_string: oracle://c%23%23testdb:testdb123@localhost:1521/FREE
    pdb_name: TESTPDB
    stream_snapshot: false
    snapshot_max_batch_size: 160000
    logminer:
      scn_window_size: 190000
      backoff_interval: 2s
      mining_interval: 0s
    include:
      - TESTDB.USERS
      - TESTDB.PRODUCTS
      - TESTDB.CART
    batching:
      count: 140000
      period: 1s

output:
  processors:
    - benchmark:
        interval: 1s
        count_bytes: true
  file:
    path: "./results.json"
    codec: lines
  # stdout: {}
  # drop: {}

logger:
  level: INFO

metrics:
  prometheus:
    add_process_metrics: true
    add_go_metrics: true
