dictionaries = ["en_us"]

words = [
    "acked",
    "acking",
    "acks",
    "activemq",
    "addrs",
    "agentic",
    "amqp",
    "amqps",
    "ansible",
    "appendf",
    "arn",
    "atoi",
    "authorizer",
    "autocommit",
    "avro",
    "backpressure",
    "batcher",
    "beanstalkd",
    "benthos",
    "bento",
    "binlog",
    "bloblang",
    "bulkable",
    "changefeed",
    "changefeeds",
    "checkpointer",
    "checkpointing",
    "chroot",
    "chunker",
    "cidr",
    "clickhouse",
    "clob",
    "cloudwatch",
    "cockroachdb",
    "couchbase",
    "creds",
    "cron",
    "cyborgdb",
    "databricks",
    "datadog",
    "dataplane",
    "dbname",
    "dbo",
    "debezium",
    "debugf",
    "decr",
    "dedup",
    "dedupe",
    "dgraph",
    "dml",
    "dsn",
    "duckdb",
    "dynamodb",
    "equalf",
    "errgroup",
    "evaluable",
    "eventbus",
    "fanout",
    "firehose",
    "fprint",
    "fprintln",
    "fqn",
    "funcs",
    "geoip",
    "gofumpt",
    "gopls",
    "goroutine",
    "goroutines",
    "hamba",
    "hashicorp",
    "hdfs",
    "hostport",
    "iam",
    "iface",
    "itoa",
    "jetstream",
    "jira",
    "jql",
    "kafka",
    "kafkastore",
    "keepalive",
    "keyspace",
    "kinesis",
    "lifecycle",
    "llm",
    "localstack",
    "logfile",
    "logminer",
    "lossy",
    "lsn",
    "materializer",
    "millis",
    "minio",
    "mockable",
    "mongodb",
    "mqtt",
    "multimodal",
    "nacked",
    "nacking",
    "nacks",
    "nanomsg",
    "nats",
    "nsq",
    "oauthbearer",
    "oci",
    "ockam",
    "ollama",
    "openai",
    "opensearch",
    "openssl",
    "opentracing",
    "oplog",
    "oracledb",
    "partitioner",
    "pdata",
    "pglogicalstream",
    "pgx",
    "pinecone",
    "postgres",
    "protoc",
    "protogen",
    "qdrant",
    "questdb",
    "rabbitmq",
    "rangefeed",
    "ratelimit",
    "ratelimiting",
    "rebalance",
    "rebalances",
    "rebalancing",
    "reconnections",
    "redis",
    "redpanda",
    "retriable",
    "runtimepb",
    "sarama",
    "sas",
    "schemaregistry",
    "scn",
    "scramsha",
    "seqno",
    "serde",
    "signaller",
    "snowpipe",
    "sns",
    "sobject",
    "sobjects",
    "soql",
    "spicedb",
    "splunk",
    "sqs",
    "sslmode",
    "sso",
    "starlark",
    "statsd",
    "streamable",
    "submatch",
    "subtest",
    "subtests",
    "syscalls",
    "tablename",
    "tbl",
    "temporality",
    "testcontainers",
    "testify",
    "tigerbeetle",
    "tiktoken",
    "timeplus",
    "timestamptz",
    "tps",
    "tracef",
    "trino",
    "udp",
    "unbuffered",
    "unmarshalling",
    "upsert",
    "upserted",
    "upserting",
    "userinfo",
    "varint",
    "waitgroup",
    "warnf",
    "worktree",
    "zeromq",
    "zmq",
]
