version: "2"

run:
  timeout: 5m
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Extra linters:
    - wastedassign
    # gocritic is very slow (golangci-lint v1.52.0)
    # - gocritic
    - revive
    - unconvert
    - durationcheck
    # - depguard
    # - bodyclose
    # - gosec
    # - misspell
    # - prealloc
    - perfsprint
    - testifylint
    - usetesting
    - predeclared
    - mirror
    - rowserrcheck
    - bodyclose
    - nolintlint
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/redpanda-data/benthos/v4/internal/batch.Error).Failed
        - (*github.com/redpanda-data/benthos/v4/public/service.BatchError).Failed
    gocritic:
      disabled-checks:
        - hugeParam # Micro-optimisations
        - rangeValCopy # Micro-optimisations
        - ifElseChain # Mostly false positives
        - ptrToRefParam # False positives?
        - importShadow # Probably not worth the hassle...
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      disable:
        - fieldalignment
        - deepequalerrors
        - shadow
      enable-all: true
    revive:
      enable-all-rules: false
      rules:
        - name: superfluous-else
        - name: exported
    testifylint:
      disable-all: true
      enable:
        - nil-compare
        - compares
        - error-is-as
        - bool-compare
        - empty
        - len
        - expected-actual
        - error-nil
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - perfsprint
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
    - gofumpt
  settings:
    goimports:
      local-prefixes:
        - github.com/redpanda-data/
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
