run:
  timeout: 30s

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  # fix: true
  include:
    - EXC0012
    - EXC0014

linters-settings:
  errcheck:
    exclude-functions:
      - (*github.com/benthosdev/benthos/v4/internal/batch.Error).Failed
      - (*github.com/benthosdev/benthos/v4/public/service.BatchError).Failed
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam # Micro-optimisations
      - rangeValCopy # Micro-optimisations
      - ifElseChain # Mostly false positives
      - ptrToRefParam # False positives?
      - importShadow # Probably not worth the hassle...
  depguard:
    include-go-root: true
    packages:
      - "io/ioutil"

linters:
  disable-all: true
  default: none
  enable:
    # Default linters reported by `golangci-lint help linters` in v1.41.1
    # Disabled for Go 1.18
    - gosimple
    - staticcheck
    - unused
    - errcheck
    - govet
    - ineffassign
    - typecheck
    # Extra linters:
    # Disabled for Go 1.18
    # - wastedassign
    - stylecheck
    - gofmt
    - goimports
    - gocritic
    - revive
    - unconvert
    - durationcheck
    - depguard
    # - bodyclose
    # - gosec
    # - misspell
    # - prealloc
    - errorlint
    - varnamelen
  settings:
    varnamelen:
      max-distance: 5
      min-name-length: 3
      check-receiver: true
      check-return: true
      check-type-param: true
      ignore-names:
        - err
        - ch
        - db
        - tx
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
formatters:
  enable:
    - gofmt
