run:
  timeout: 30s

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  # fix: true

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam # Micro-optimisations
      - rangeValCopy # Micro-optimisations
      - ifElseChain # Mostly false positives
      - ptrToRefParam # False positives?
      - importShadow # Probably not worth the hassle...
      # TODO
      - sloppyReassign
      - singleCaseSwitch
      - regexpMust
      - commentFormatting
      - captLocal
      - elseif
      - commentedOutCode
      - emptyFallthrough
      - typeAssertChain
      - initClause
      - unslice
      - appendCombine
      - emptyStringTest
      - assignOp
      - octalLiteral
      - builtinShadow
      - unlabelStmt
      - wrapperFunc
      - paramTypeCombine
      - unlambda
      - yodaStyleExpr
      - unnamedResult
      - exitAfterDefer
      - valSwap
      - typeUnparen
      - appendAssign
      - deprecatedComment
      - nestingReduce

linters:
  disable-all: true
  enable:
    # Default linters reported by golangci-lint help linters` in v1.39.0
    # - deadcode
    # - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    # - unused
    - varcheck
    # Extra linters:
    - gofmt
    - goimports
    - gocritic
    # - bodyclose
