builds:
  - id: benthos
    main: cmd/benthos/main.go
    binary: benthos
    goos: [ windows, darwin, linux ]
    goarch: [ amd64, arm ]
    goarm: [ 5, 6, 7 ]
    ldflags: >
      -X main.Version={{.Version}}
      -X main.DateBuilt={{.Date}}
  - id: benthos-lambda
    main: cmd/serverless/benthos-lambda/main.go
    binary: benthos-lambda
    goos: [ linux ]
    goarch: [ amd64 ]
archives:
  - id: benthos
    format: tar.gz
    files:
      - README.md
      - CHANGELOG.md
      - LICENSE
      - config/*
      - config/**/*
      - docs/*
      - docs/**/*
  - id: benthos-lambda
    format: zip
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
dist: target/dist
changelog:
  filters:
    exclude:
      - .*
release:
  github:
    owner: Jeffail
    name: benthos
  disable: false