version: '3.3'
services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    command: >
      postgres
        -c wal_level=logical
        -c max_replication_slots=4
        -c max_wal_senders=4
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo"]
      interval: 3s
      timeout: 3s
      retries: 10

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda
    ports:
      - 8081:8081
      - 9092:9092
    command:
      - 'redpanda start'
      - '--smp 1'
      - '--overprovisioned'
      - '--kafka-addr 0.0.0.0:9092'
      - '--advertise-kafka-addr localhost:9092'
      - '--pandaproxy-addr 0.0.0.0:8082'
      - '--advertise-pandaproxy-addr localhost:8082'
