FROM confluentinc/cp-server-connect-base:7.7.8
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-s3:10.5.23
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-s3-source:latest
