# Copyright 2024 Redpanda Data, Inc.
#
# Licensed as a Redpanda Enterprise file under the Redpanda Community
# License (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# https://github.com/redpanda-data/connect/blob/main/licenses/rcl.md

FROM golang:1.24 AS build

ENV CGO_ENABLED=0
ENV GOOS=linux
RUN useradd -u 10001 connect

RUN apt-get update && apt-get install -y libcap2-bin
RUN go install github.com/go-task/task/v3/cmd/task@latest

WORKDIR /go/src/github.com/redpanda-data/connect/
# Update dependencies: On unchanged dependencies, cached layer will be reused
COPY go.* /go/src/github.com/redpanda-data/connect/
RUN go mod download

# Build
COPY . /go/src/github.com/redpanda-data/connect/
# Tag timetzdata required for busybox base image:
# https://github.com/benthosdev/benthos/issues/897
RUN TAGS="timetzdata" task build:redpanda-connect-ai
RUN setcap 'cap_sys_chroot=+ep' target/redpanda-connect-ai

RUN touch /tmp/keep

# Pack
FROM ollama/ollama AS package

# Override the HOST from the ollama dockerfile
ENV OLLAMA_HOST=127.0.0.1

LABEL maintainer="Tyler Rockwood <rockwood@redpanda.com>"
LABEL org.opencontainers.image.source="https://github.com/redpanda-data/connect"

WORKDIR /

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/passwd /etc/passwd
COPY --from=build /go/src/github.com/redpanda-data/connect/target/redpanda-connect-ai ./redpanda-connect
COPY ./config/docker.yaml /connect.yaml

USER connect

COPY --chown=connect:connect --from=build /tmp/keep /home/connect/.ollama/keep

EXPOSE 4195

ENTRYPOINT ["/redpanda-connect"]

CMD ["run", "/connect.yaml"]
