{
 "title": "Benthos Profiling",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Input Rate (30s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    { "expr": "rate(input_received{}[30s])" }
   ]
  },
  {
   "title": "Output Rate (30s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    { "expr": "rate(output_sent{}[30s])" }
   ]
  },
  {
   "title": "Transaction Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expr": "output_latency_ns{}" }
   ]
  },
  {
   "title": "Processor Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expr": "processor_latency_ns{}" }
   ]
  }
 ]
}