// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BearerAuth provides bearerAuth security value.
	BearerAuth(ctx context.Context, operationName OperationName) (BearerAuth, error)
}

// operationRolesBearerAuth is a private map storing roles per operation.
var operationRolesBearerAuth = map[string][]string{
	V1BlocksIDChildrenGetOperation:                []string{},
	V1BlocksIDChildrenPatchOperation:              []string{},
	V1BlocksIDDeleteOperation:                     []string{},
	V1BlocksIDGetOperation:                        []string{},
	V1BlocksIDPatchOperation:                      []string{},
	V1CommentsGetOperation:                        []string{},
	V1CommentsPostOperation:                       []string{},
	V1DatabasesIDGetOperation:                     []string{},
	V1DatabasesIDPatchOperation:                   []string{},
	V1DatabasesIDQueryPostOperation:               []string{},
	V1DatabasesPostOperation:                      []string{},
	V1PagesIDGetOperation:                         []string{},
	V1PagesIDPatchOperation:                       []string{},
	V1PagesPageIDPropertiesPropertyIDGetOperation: []string{},
	V1PagesPostOperation:                          []string{},
	V1SearchPostOperation:                         []string{},
	V1UsersGetOperation:                           []string{},
	V1UsersIDGetOperation:                         []string{},
	V1UsersMeGetOperation:                         []string{},
}

// GetRolesForBearerAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBearerAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBearerAuth(operation string) []string {
	roles, ok := operationRolesBearerAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Client) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
