// Code generated by ogen, DO NOT EDIT.

package api

import (
	"bytes"
	"net/http"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	ht "github.com/ogen-go/ogen/http"
)

func encodeV1BlocksIDChildrenPatchRequest(
	req *V1BlocksIDChildrenPatchReqWithContentType,
	r *http.Request,
) error {
	contentType := req.ContentType
	if contentType != "" && !ht.MatchContentType("*/*", contentType) {
		return errors.Errorf("%q does not match mask %q", contentType, "*/*")
	}
	{
		req := req.Content
		body := req
		ht.SetBody(r, body, contentType)
		return nil
	}
}

func encodeV1BlocksIDPatchRequest(
	req *V1BlocksIDPatchReq,
	r *http.Request,
) error {
	const contentType = "application/json"
	e := new(jx.Encoder)
	{
		if req != nil {
			req.Encode(e)
		}
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeV1CommentsPostRequest(
	req *V1CommentsPostReqWithContentType,
	r *http.Request,
) error {
	contentType := req.ContentType
	if contentType != "" && !ht.MatchContentType("*/*", contentType) {
		return errors.Errorf("%q does not match mask %q", contentType, "*/*")
	}
	{
		req := req.Content
		body := req
		ht.SetBody(r, body, contentType)
		return nil
	}
}

func encodeV1DatabasesIDPatchRequest(
	req *V1DatabasesIDPatchReq,
	r *http.Request,
) error {
	const contentType = "application/json"
	e := new(jx.Encoder)
	{
		if req != nil {
			req.Encode(e)
		}
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeV1DatabasesIDQueryPostRequest(
	req *V1DatabasesIDQueryPostReqWithContentType,
	r *http.Request,
) error {
	contentType := req.ContentType
	if contentType != "" && !ht.MatchContentType("*/*", contentType) {
		return errors.Errorf("%q does not match mask %q", contentType, "*/*")
	}
	{
		req := req.Content
		body := req
		ht.SetBody(r, body, contentType)
		return nil
	}
}

func encodeV1DatabasesPostRequest(
	req *V1DatabasesPostReqWithContentType,
	r *http.Request,
) error {
	contentType := req.ContentType
	if contentType != "" && !ht.MatchContentType("*/*", contentType) {
		return errors.Errorf("%q does not match mask %q", contentType, "*/*")
	}
	{
		req := req.Content
		body := req
		ht.SetBody(r, body, contentType)
		return nil
	}
}

func encodeV1PagesIDPatchRequest(
	req *V1PagesIDPatchReq,
	r *http.Request,
) error {
	const contentType = "application/json"
	e := new(jx.Encoder)
	{
		if req != nil {
			req.Encode(e)
		}
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}

func encodeV1PagesPostRequest(
	req *V1PagesPostReqWithContentType,
	r *http.Request,
) error {
	contentType := req.ContentType
	if contentType != "" && !ht.MatchContentType("*/*", contentType) {
		return errors.Errorf("%q does not match mask %q", contentType, "*/*")
	}
	{
		req := req.Content
		body := req
		ht.SetBody(r, body, contentType)
		return nil
	}
}

func encodeV1SearchPostRequest(
	req *V1SearchPostReqWithContentType,
	r *http.Request,
) error {
	contentType := req.ContentType
	if contentType != "" && !ht.MatchContentType("*/*", contentType) {
		return errors.Errorf("%q does not match mask %q", contentType, "*/*")
	}
	{
		req := req.Content
		body := req
		ht.SetBody(r, body, contentType)
		return nil
	}
}
