//
// Salesforce Pub/Sub API Version 1.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: pubsub_api.proto

package salesforcegrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PubSub_Subscribe_FullMethodName        = "/eventbus.v1.PubSub/Subscribe"
	PubSub_GetSchema_FullMethodName        = "/eventbus.v1.PubSub/GetSchema"
	PubSub_GetTopic_FullMethodName         = "/eventbus.v1.PubSub/GetTopic"
	PubSub_Publish_FullMethodName          = "/eventbus.v1.PubSub/Publish"
	PubSub_PublishStream_FullMethodName    = "/eventbus.v1.PubSub/PublishStream"
	PubSub_ManagedSubscribe_FullMethodName = "/eventbus.v1.PubSub/ManagedSubscribe"
)

// PubSubClient is the client API for PubSub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Pub/Sub API provides a single interface for publishing and subscribing to platform events, including real-time
// event monitoring events, and change data capture events. The Pub/Sub API is a gRPC API that is based on HTTP/2.
//
// A session token is needed to authenticate. Any of the Salesforce supported
// OAuth flows can be used to obtain a session token:
// https://help.salesforce.com/articleView?id=sf.remoteaccess_oauth_flows.htm&type=5
//
// For each RPC, a client needs to pass authentication information
// as metadata headers (https://www.grpc.io/docs/guides/concepts/#metadata) with their method call.
//
// For Salesforce session token authentication, use:
//
//	accesstoken : access token
//	instanceurl : Salesforce instance URL
//	tenantid : tenant/org id of the client
//
// StatusException is thrown in case of response failure for any request.
type PubSubClient interface {
	// Bidirectional streaming RPC to subscribe to a Topic. The subscription is pull-based. A client can request
	// for more events as it consumes events. This enables a client to handle flow control based on the client's processing speed.
	//
	// Typical flow:
	//  1. Client requests for X number of events via FetchRequest.
	//  2. Server receives request and delivers events until X events are delivered to the client via one or more FetchResponse messages.
	//  3. Client consumes the FetchResponse messages as they come.
	//  4. Client issues new FetchRequest for Y more number of events. This request can
	//     come before the server has delivered the earlier requested X number of events
	//     so the client gets a continuous stream of events if any.
	//
	// If a client requests more events before the server finishes the last
	// requested amount, the server appends the new amount to the current amount of
	// events it still needs to fetch and deliver.
	//
	// A client can subscribe at any point in the stream by providing a replay option in the first FetchRequest.
	// The replay option is honored for the first FetchRequest received from a client. Any subsequent FetchRequests with a
	// new replay option are ignored. A client needs to call the Subscribe RPC again to restart the subscription
	// at a new point in the stream.
	//
	// The first FetchRequest of the stream identifies the topic to subscribe to.
	// If any subsequent FetchRequest provides topic_name, it must match what
	// was provided in the first FetchRequest; otherwise, the RPC returns an error
	// with INVALID_ARGUMENT status.
	Subscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FetchRequest, FetchResponse], error)
	// Get the event schema for a topic based on a schema ID.
	GetSchema(ctx context.Context, in *SchemaRequest, opts ...grpc.CallOption) (*SchemaInfo, error)
	// Get the topic Information related to the specified topic.
	GetTopic(ctx context.Context, in *TopicRequest, opts ...grpc.CallOption) (*TopicInfo, error)
	// Send a publish request to synchronously publish events to a topic.
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	// Bidirectional Streaming RPC to publish events to the event bus.
	// PublishRequest contains the batch of events to publish.
	//
	// The first PublishRequest of the stream identifies the topic to publish on.
	// If any subsequent PublishRequest provides topic_name, it must match what
	// was provided in the first PublishRequest; otherwise, the RPC returns an error
	// with INVALID_ARGUMENT status.
	//
	// The server returns a PublishResponse for each PublishRequest when publish is
	// complete for the batch. A client does not have to wait for a PublishResponse
	// before sending a new PublishRequest, i.e. multiple publish batches can be queued
	// up, which allows for higher publish rate as a client can asynchronously
	// publish more events while publishes are still in flight on the server side.
	//
	// PublishResponse holds a PublishResult for each event published that indicates success
	// or failure of the publish. A client can then retry the publish as needed before sending
	// more PublishRequests for new events to publish.
	//
	// A client must send a valid publish request with one or more events every 70 seconds to hold on to the stream.
	// Otherwise, the server closes the stream and notifies the client. Once the client is notified of the stream closure,
	// it must make a new PublishStream call to resume publishing.
	PublishStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PublishRequest, PublishResponse], error)
	// This feature is part of an open beta release and is subject to the applicable
	// Beta Services Terms provided at Agreements and Terms
	// (https://www.salesforce.com/company/legal/agreements/).
	//
	// Same as Subscribe, but for Managed Subscription clients.
	// This feature is part of an open beta release.
	ManagedSubscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ManagedFetchRequest, ManagedFetchResponse], error)
}

type pubSubClient struct {
	cc grpc.ClientConnInterface
}

func NewPubSubClient(cc grpc.ClientConnInterface) PubSubClient {
	return &pubSubClient{cc}
}

func (c *pubSubClient) Subscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FetchRequest, FetchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PubSub_ServiceDesc.Streams[0], PubSub_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchRequest, FetchResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PubSub_SubscribeClient = grpc.BidiStreamingClient[FetchRequest, FetchResponse]

func (c *pubSubClient) GetSchema(ctx context.Context, in *SchemaRequest, opts ...grpc.CallOption) (*SchemaInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchemaInfo)
	err := c.cc.Invoke(ctx, PubSub_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubClient) GetTopic(ctx context.Context, in *TopicRequest, opts ...grpc.CallOption) (*TopicInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopicInfo)
	err := c.cc.Invoke(ctx, PubSub_GetTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, PubSub_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubClient) PublishStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PublishRequest, PublishResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PubSub_ServiceDesc.Streams[1], PubSub_PublishStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PublishRequest, PublishResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PubSub_PublishStreamClient = grpc.BidiStreamingClient[PublishRequest, PublishResponse]

func (c *pubSubClient) ManagedSubscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ManagedFetchRequest, ManagedFetchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PubSub_ServiceDesc.Streams[2], PubSub_ManagedSubscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ManagedFetchRequest, ManagedFetchResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PubSub_ManagedSubscribeClient = grpc.BidiStreamingClient[ManagedFetchRequest, ManagedFetchResponse]

// PubSubServer is the server API for PubSub service.
// All implementations must embed UnimplementedPubSubServer
// for forward compatibility.
//
// The Pub/Sub API provides a single interface for publishing and subscribing to platform events, including real-time
// event monitoring events, and change data capture events. The Pub/Sub API is a gRPC API that is based on HTTP/2.
//
// A session token is needed to authenticate. Any of the Salesforce supported
// OAuth flows can be used to obtain a session token:
// https://help.salesforce.com/articleView?id=sf.remoteaccess_oauth_flows.htm&type=5
//
// For each RPC, a client needs to pass authentication information
// as metadata headers (https://www.grpc.io/docs/guides/concepts/#metadata) with their method call.
//
// For Salesforce session token authentication, use:
//
//	accesstoken : access token
//	instanceurl : Salesforce instance URL
//	tenantid : tenant/org id of the client
//
// StatusException is thrown in case of response failure for any request.
type PubSubServer interface {
	// Bidirectional streaming RPC to subscribe to a Topic. The subscription is pull-based. A client can request
	// for more events as it consumes events. This enables a client to handle flow control based on the client's processing speed.
	//
	// Typical flow:
	//  1. Client requests for X number of events via FetchRequest.
	//  2. Server receives request and delivers events until X events are delivered to the client via one or more FetchResponse messages.
	//  3. Client consumes the FetchResponse messages as they come.
	//  4. Client issues new FetchRequest for Y more number of events. This request can
	//     come before the server has delivered the earlier requested X number of events
	//     so the client gets a continuous stream of events if any.
	//
	// If a client requests more events before the server finishes the last
	// requested amount, the server appends the new amount to the current amount of
	// events it still needs to fetch and deliver.
	//
	// A client can subscribe at any point in the stream by providing a replay option in the first FetchRequest.
	// The replay option is honored for the first FetchRequest received from a client. Any subsequent FetchRequests with a
	// new replay option are ignored. A client needs to call the Subscribe RPC again to restart the subscription
	// at a new point in the stream.
	//
	// The first FetchRequest of the stream identifies the topic to subscribe to.
	// If any subsequent FetchRequest provides topic_name, it must match what
	// was provided in the first FetchRequest; otherwise, the RPC returns an error
	// with INVALID_ARGUMENT status.
	Subscribe(grpc.BidiStreamingServer[FetchRequest, FetchResponse]) error
	// Get the event schema for a topic based on a schema ID.
	GetSchema(context.Context, *SchemaRequest) (*SchemaInfo, error)
	// Get the topic Information related to the specified topic.
	GetTopic(context.Context, *TopicRequest) (*TopicInfo, error)
	// Send a publish request to synchronously publish events to a topic.
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	// Bidirectional Streaming RPC to publish events to the event bus.
	// PublishRequest contains the batch of events to publish.
	//
	// The first PublishRequest of the stream identifies the topic to publish on.
	// If any subsequent PublishRequest provides topic_name, it must match what
	// was provided in the first PublishRequest; otherwise, the RPC returns an error
	// with INVALID_ARGUMENT status.
	//
	// The server returns a PublishResponse for each PublishRequest when publish is
	// complete for the batch. A client does not have to wait for a PublishResponse
	// before sending a new PublishRequest, i.e. multiple publish batches can be queued
	// up, which allows for higher publish rate as a client can asynchronously
	// publish more events while publishes are still in flight on the server side.
	//
	// PublishResponse holds a PublishResult for each event published that indicates success
	// or failure of the publish. A client can then retry the publish as needed before sending
	// more PublishRequests for new events to publish.
	//
	// A client must send a valid publish request with one or more events every 70 seconds to hold on to the stream.
	// Otherwise, the server closes the stream and notifies the client. Once the client is notified of the stream closure,
	// it must make a new PublishStream call to resume publishing.
	PublishStream(grpc.BidiStreamingServer[PublishRequest, PublishResponse]) error
	// This feature is part of an open beta release and is subject to the applicable
	// Beta Services Terms provided at Agreements and Terms
	// (https://www.salesforce.com/company/legal/agreements/).
	//
	// Same as Subscribe, but for Managed Subscription clients.
	// This feature is part of an open beta release.
	ManagedSubscribe(grpc.BidiStreamingServer[ManagedFetchRequest, ManagedFetchResponse]) error
	mustEmbedUnimplementedPubSubServer()
}

// UnimplementedPubSubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPubSubServer struct{}

func (UnimplementedPubSubServer) Subscribe(grpc.BidiStreamingServer[FetchRequest, FetchResponse]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedPubSubServer) GetSchema(context.Context, *SchemaRequest) (*SchemaInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedPubSubServer) GetTopic(context.Context, *TopicRequest) (*TopicInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopic not implemented")
}
func (UnimplementedPubSubServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedPubSubServer) PublishStream(grpc.BidiStreamingServer[PublishRequest, PublishResponse]) error {
	return status.Error(codes.Unimplemented, "method PublishStream not implemented")
}
func (UnimplementedPubSubServer) ManagedSubscribe(grpc.BidiStreamingServer[ManagedFetchRequest, ManagedFetchResponse]) error {
	return status.Error(codes.Unimplemented, "method ManagedSubscribe not implemented")
}
func (UnimplementedPubSubServer) mustEmbedUnimplementedPubSubServer() {}
func (UnimplementedPubSubServer) testEmbeddedByValue()                {}

// UnsafePubSubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PubSubServer will
// result in compilation errors.
type UnsafePubSubServer interface {
	mustEmbedUnimplementedPubSubServer()
}

func RegisterPubSubServer(s grpc.ServiceRegistrar, srv PubSubServer) {
	// If the following call panics, it indicates UnimplementedPubSubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PubSub_ServiceDesc, srv)
}

func _PubSub_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PubSubServer).Subscribe(&grpc.GenericServerStream[FetchRequest, FetchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PubSub_SubscribeServer = grpc.BidiStreamingServer[FetchRequest, FetchResponse]

func _PubSub_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubSub_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServer).GetSchema(ctx, req.(*SchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSub_GetTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServer).GetTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubSub_GetTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServer).GetTopic(ctx, req.(*TopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSub_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubSub_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSub_PublishStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PubSubServer).PublishStream(&grpc.GenericServerStream[PublishRequest, PublishResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PubSub_PublishStreamServer = grpc.BidiStreamingServer[PublishRequest, PublishResponse]

func _PubSub_ManagedSubscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PubSubServer).ManagedSubscribe(&grpc.GenericServerStream[ManagedFetchRequest, ManagedFetchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PubSub_ManagedSubscribeServer = grpc.BidiStreamingServer[ManagedFetchRequest, ManagedFetchResponse]

// PubSub_ServiceDesc is the grpc.ServiceDesc for PubSub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PubSub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eventbus.v1.PubSub",
	HandlerType: (*PubSubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSchema",
			Handler:    _PubSub_GetSchema_Handler,
		},
		{
			MethodName: "GetTopic",
			Handler:    _PubSub_GetTopic_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _PubSub_Publish_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _PubSub_Subscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PublishStream",
			Handler:       _PubSub_PublishStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ManagedSubscribe",
			Handler:       _PubSub_ManagedSubscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pubsub_api.proto",
}
