{
 "title": "Benthos Profiling",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Input/Output Messages Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(input_received{}[$__rate_interval])"
    },
    {
     "expr": "rate(output_sent{}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Size Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(output_sent[$__rate_interval])/rate(output_batch_sent[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Transaction Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expr": "output_latency_ns" }
   ]
  },
  {
   "title": "Processor Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expr": "processor_latency_ns" }
   ]
  },
  { "title": "Benchmark", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Bytes Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(benchmark_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}