{
 "title": "Benthos Dash",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "In v Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(benthos_input_read_success[30s])",
     "legendFormat": "Input"
    },
    {
     "expr": "rate(benthos_output_success[30s])",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Input Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "benthos_input_latency", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Buffer Use",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(benthos_buffer_backlog[10s])",
     "legendFormat": "Backlog"
    }
   ]
  },
  {
   "title": "Buffer Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "benthos_buffer_latency", "legendFormat": "{{quantile}}" }
   ]
  }
 ]
}