version: '3'

vars:
  LD_FLAGS: '{{default "-w -s" .LD_FLAGS}}'
  DATE_BUILT: '{{now | date "2006-01-02T15:04:05Z"}}'
  GO_BUILD_CMD: go build {{.GO_FLAGS}} -tags "{{.TAGS}}" -ldflags "{{.LD_FLAGS}} -X main.Version=v{{.VERSION}} -X main.DateBuilt={{.DATE_BUILT}}"

tasks:
  all:
    desc: Build all apps
    deps:
      - redpanda-connect
      - redpanda-connect-cloud
      - redpanda-connect-community
      - redpanda-connect-ai

  redpanda-connect:
    desc: Build redpanda-connect
    method: timestamp
    sources:
      - internal/**
      - public/**
      - go.mod
      - go.sum
    generates:
      - '{{.TARGET_DIR}}/redpanda-connect'
    cmds:
      - task: :target-dir
      - '{{.GO_BUILD_CMD}} -o {{.TARGET_DIR}}/redpanda-connect ./cmd/redpanda-connect'

  redpanda-connect-cloud:
    desc: Build redpanda-connect-cloud
    method: timestamp
    sources:
      - internal/**
      - public/**
      - go.mod
      - go.sum
    generates:
      - '{{.TARGET_DIR}}/redpanda-connect-cloud'
    cmds:
      - task: :target-dir
      - '{{.GO_BUILD_CMD}} -o {{.TARGET_DIR}}/redpanda-connect-cloud ./cmd/redpanda-connect-cloud'

  redpanda-connect-community:
    desc: Build redpanda-connect-community
    method: timestamp
    sources:
      - internal/**
      - public/**
      - go.mod
      - go.sum
    generates:
      - '{{.TARGET_DIR}}/redpanda-connect-community'
    cmds:
      - task: :target-dir
      - '{{.GO_BUILD_CMD}} -o {{.TARGET_DIR}}/redpanda-connect-community ./cmd/redpanda-connect-community'

  redpanda-connect-ai:
    desc: Build redpanda-connect-ai
    method: timestamp
    sources:
      - internal/**
      - public/**
      - go.mod
      - go.sum
    generates:
      - '{{.TARGET_DIR}}/redpanda-connect-ai'
    cmds:
      - task: :target-dir
      - '{{.GO_BUILD_CMD}} -o {{.TARGET_DIR}}/redpanda-connect-ai ./cmd/redpanda-connect-ai'

  :target-dir:
    internal: true
    cmds:
      - mkdir -p '{{.TARGET_DIR}}'

  skills:
    desc: Build Claude Code skill ZIPs
    vars:
      PLUGIN_VERSION:
        sh: jq -r '.version' .claude-plugin/plugins/redpanda-connect/.claude-plugin/plugin.json
    sources:
      - .claude-plugin/plugins/redpanda-connect/skills/**/*.md
      - .claude-plugin/plugins/redpanda-connect/skills/**/*.py
      - .claude-plugin/plugins/redpanda-connect/skills/**/*.sh
      - .claude-plugin/plugins/redpanda-connect/skills/**/*.yaml
      - .claude-plugin/plugins/redpanda-connect/.claude-plugin/plugin.json
    generates:
      - '{{.TARGET_DIR}}/skills/bloblang-authoring.zip'
      - '{{.TARGET_DIR}}/skills/component-search.zip'
      - '{{.TARGET_DIR}}/skills/pipeline-assistant.zip'
      - .claude-plugin/dist/bloblang-authoring-{{.PLUGIN_VERSION}}.zip
      - .claude-plugin/dist/component-search-{{.PLUGIN_VERSION}}.zip
      - .claude-plugin/dist/pipeline-assistant-{{.PLUGIN_VERSION}}.zip
    cmds:
      - mkdir -p .claude-plugin/dist
      - |
        BUILD_DIR=$(pwd)/.claude-plugin/dist
        cd .claude-plugin/plugins/redpanda-connect/skills
        for skill in bloblang-authoring component-search pipeline-assistant; do
          cd $skill && zip -q -r "$BUILD_DIR/$skill-{{.PLUGIN_VERSION}}.zip" . -x ".*" -x "__pycache__/*" -x "*.pyc" && cd ..
          echo "✓ Built $skill-{{.PLUGIN_VERSION}}.zip"
        done

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.TARGET_DIR}}
