// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BearerAuth provides bearerAuth security value.
	BearerAuth(ctx context.Context, operationName OperationName) (BearerAuth, error)
}

// operationRolesBearerAuth is a private map storing roles per operation.
var operationRolesBearerAuth = map[string][]string{
	BlocksIDChildrenGetOperation:                []string{},
	BlocksIDChildrenPatchOperation:              []string{},
	BlocksIDDeleteOperation:                     []string{},
	BlocksIDGetOperation:                        []string{},
	BlocksIDPatchOperation:                      []string{},
	CommentsGetOperation:                        []string{},
	CommentsPostOperation:                       []string{},
	DatabasesIDGetOperation:                     []string{},
	DatabasesIDPatchOperation:                   []string{},
	DatabasesIDQueryPostOperation:               []string{},
	DatabasesPostOperation:                      []string{},
	PagesIDGetOperation:                         []string{},
	PagesIDPatchOperation:                       []string{},
	PagesPageIDPropertiesPropertyIDGetOperation: []string{},
	PagesPostOperation:                          []string{},
	SearchPostOperation:                         []string{},
	UsersGetOperation:                           []string{},
	UsersIDGetOperation:                         []string{},
	UsersMeGetOperation:                         []string{},
}

// GetRolesForBearerAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBearerAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBearerAuth(operation string) []string {
	roles, ok := operationRolesBearerAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Client) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
