// Code generated by ogen, DO NOT EDIT.

package v1

// OperationName is the ogen operation name
type OperationName = string

const (
	BlocksIDChildrenGetOperation                OperationName = "BlocksIDChildrenGet"
	BlocksIDChildrenPatchOperation              OperationName = "BlocksIDChildrenPatch"
	BlocksIDDeleteOperation                     OperationName = "BlocksIDDelete"
	BlocksIDGetOperation                        OperationName = "BlocksIDGet"
	BlocksIDPatchOperation                      OperationName = "BlocksIDPatch"
	CommentsGetOperation                        OperationName = "CommentsGet"
	CommentsPostOperation                       OperationName = "CommentsPost"
	DatabasesIDGetOperation                     OperationName = "DatabasesIDGet"
	DatabasesIDPatchOperation                   OperationName = "DatabasesIDPatch"
	DatabasesIDQueryPostOperation               OperationName = "DatabasesIDQueryPost"
	DatabasesPostOperation                      OperationName = "DatabasesPost"
	PagesIDGetOperation                         OperationName = "PagesIDGet"
	PagesIDPatchOperation                       OperationName = "PagesIDPatch"
	PagesPageIDPropertiesPropertyIDGetOperation OperationName = "PagesPageIDPropertiesPropertyIDGet"
	PagesPostOperation                          OperationName = "PagesPost"
	SearchPostOperation                         OperationName = "SearchPost"
	UsersGetOperation                           OperationName = "UsersGet"
	UsersIDGetOperation                         OperationName = "UsersIDGet"
	UsersMeGetOperation                         OperationName = "UsersMeGet"
)
