name: 'Setup Task'
description: 'Install Task'

runs:
  using: "composite"
  steps:
    - name: Install Task
      shell: bash
      run: |
        sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "Installed Task version: $(~/.local/bin/task --version)"
