services:

  src:
    cpuset: "2"
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_AGENT_ENABLED: true
    ports:
      - "1433:1433"

  connect:
    image: redpandadata/connect
    # depends_on:
    #   src:
    #     condition: service_healthy
    volumes:
      - ./config.yaml:/config.yaml:ro
    command: ["-c", "/config.yaml"]
    ports:
      - "4195:4195"
    environment:
      GOMAXPROCS: "3"
      GOMEMLIMIT: "3GiB"
    cpuset: "5,6,7"
    mem_limit: 3500M
