version: '3'

tasks:
  default:
    - task: down
    - task: up
    - task: logs:connect

  up:
    cmd: docker compose up -d

  down:
    cmd: docker compose down -v --remove-orphans

  logs:sqlserver:
    cmd: docker compose logs -f src

  logs:connect:
    cmd: docker compose logs -f connect
