// Copyright 2024 Redpanda Data, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// docs_gen writes the generated reference content under docs/modules. The
// docs site merges that directory with the pages in rp-connect-docs; see
// docs/README.md.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/redpanda-data/connect/v4/internal/plugins"
	"github.com/redpanda-data/connect/v4/public/schema"

	_ "github.com/redpanda-data/connect/v4/cmd/tools/docs_gen/allcomponents"
)

const (
	bannerPrefix    = "// This content is autogenerated from the component specs in https://github.com/redpanda-data/connect. Do not edit manually."
	generatedBanner = bannerPrefix + " To change it, edit the component spec and run `task docs` in that repository."
	metadataBanner  = bannerPrefix + " Metadata fields come from the `== Metadata` section of the component description. To change them, edit the component spec and run `task docs` in that repository."
	descBanner      = bannerPrefix + " The summary and description come from the component spec. To change them, edit the spec and run `task docs` in that repository.\n" +
		"//\n" +
		"// Pages consume this partial in two places so both stay fresh:\n" +
		"//   header: include::...[tag=meta]  (sets :description: for search snippets and meta tags)\n" +
		"//   body:   include::...[tag=body]   (renders the status notice, summary, and description)\n" +
		"// Pages with reference sections also include [tag=footnotes] where those sections belong."
)

const (
	emptyMetadataPartial    = bannerPrefix + " The component description has no Metadata section, so this partial is empty.\n"
	emptyDescriptionPartial = bannerPrefix + " The component has no summary or description, so this partial is empty.\n" +
		"\n// tag::meta[]\n// end::meta[]\n\n// tag::body[]\n// end::body[]\n\n// tag::footnotes[]\n// end::footnotes[]\n"
)

// generatedDirs are the directories under the components module that this
// tool owns. They are emptied before every run so that a component removed
// from the code also disappears from the docs.
var generatedDirs = []string{
	"partials/fields",
	"partials/examples",
	"partials/metadata",
	"partials/descriptions",
	"partials/availability",
	"partials/platforms",
	"partials/bloblang",
	"partials/bloblang-functions",
	"partials/bloblang-methods",
	"examples/common",
	"examples/advanced",
}

var pageTypeDirs = map[string]bool{
	"inputs": true, "outputs": true, "processors": true, "caches": true, "rate_limits": true,
	"buffers": true, "metrics": true, "scanners": true, "tracers": true,
}

func main() {
	root := "./docs/modules/components"
	flag.StringVar(&root, "dir", root, "The components module directory to write docs to")
	flag.Parse()

	raw, err := schema.Standard("", "").MarshalJSONV0()
	if err != nil {
		panic(err)
	}
	full, err := parseFullSchema(raw)
	if err != nil {
		panic(err)
	}

	// Platforms come first, so a failure leaves the committed docs in place.
	plat, err := loadPlatforms(full)
	if err != nil {
		panic(fmt.Errorf("finding the components that only cgo builds include: %w", err))
	}
	if builtWithAllComponents && len(plat.cgoOnlyKeys()) == 0 {
		// x_benthos_extra exists to add components, so a full build that finds
		// none means the standard build didn't run the way it should.
		panic("found no cgo-only components in a build with x_benthos_extra; check that componentlist runs with CGO_ENABLED=0 and no build tags")
	}
	fmt.Printf("Components that only cgo builds include: %v\n", strings.Join(plat.cgoOnlyKeys(), ", "))

	// Only a build with every component can tell which files are stale. Two
	// build constraints add components: x_benthos_extra adds zmq4 (which also
	// needs cgo and libzmq) and ffi (pure Go), and cgo adds tigerbeetle_cdc. A
	// tagged build can't compile without cgo, so builtWithAllComponents also
	// implies cgo. A partial build would delete the docs of the missing
	// components, so it keeps existing files instead.
	if builtWithAllComponents {
		for _, d := range generatedDirs {
			if err := os.RemoveAll(filepath.Join(root, d)); err != nil {
				panic(err)
			}
		}
	} else {
		fmt.Fprintln(os.Stderr, "Built without x_benthos_extra: keeping existing files, so docs for removed components are not pruned. CI runs `CGO_ENABLED=1 TAGS=x_benthos_extra task docs`.")
	}

	w := writer{root: root, platforms: plat}
	for _, g := range full.Groups {
		for _, c := range g.Components {
			if c.Name != "" {
				w.component(g.Key, c)
			}
		}
	}
	if builtWithAllComponents {
		w.platformFiles(full)
	} else {
		fmt.Fprintln(os.Stderr, "Built without x_benthos_extra: keeping the existing component catalog and cgo-only list, which need every component.")
	}
	for _, f := range visibleBloblang(full.BloblangFunctions) {
		w.write(filepath.Join("partials/bloblang-functions", f.Name+".adoc"), renderBloblangSpec(f, "function"))
	}
	for _, m := range visibleBloblang(full.BloblangMethods) {
		w.write(filepath.Join("partials/bloblang-methods", m.Name+".adoc"), renderBloblangSpec(m, "method"))
	}
	// The Cloud build only allows pure Bloblang, so its schema decides which
	// functions and methods the Cloud docs list.
	cloudRaw, err := schema.Cloud("", "").MarshalJSONV0()
	if err != nil {
		panic(err)
	}
	cloud, err := parseFullSchema(cloudRaw)
	if err != nil {
		panic(err)
	}
	w.write("partials/bloblang/functions.adoc", renderFunctionsList(full.BloblangFunctions, bloblangNames(cloud.BloblangFunctions)))
	w.write("partials/bloblang/methods.adoc", renderMethodsList(full.BloblangMethods, bloblangNames(cloud.BloblangMethods)))
	w.configObjects(raw)

	fmt.Printf("Wrote %v files to %v\n", w.count, root)
}

type writer struct {
	root      string
	count     int
	platforms platformSet
}

// platformFiles writes the component catalog and the cgo-only list.
func (w *writer) platformFiles(full *fullSchema) {
	catalog, err := renderCatalog(full, w.platforms, plugins.BaseInfo)
	if err != nil {
		panic(err)
	}
	w.write("partials/platforms/catalog.json", catalog)
	w.write("partials/availability/cgo_only.adoc", renderCgoOnlyList(full, w.platforms))
}

func (w *writer) write(rel, content string) {
	p := filepath.Join(w.root, rel)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		panic(err)
	}
	w.count++
}

func (w *writer) component(key string, c componentSpec) {
	typeDir := pageTypeDir(key)
	file := c.Name + ".adoc"

	if len(c.Config.Children) > 0 {
		w.write(filepath.Join("partials/fields", key, file),
			generatedBanner+"\n\n== Fields\n\n"+renderFields(c.Config.Children, "")+"\n")
	}
	if !pageTypeDirs[typeDir] {
		return
	}
	if examples := renderComponentExamples(c.Examples); strings.TrimSpace(examples) != "" {
		w.write(filepath.Join("partials/examples", key, file),
			generatedBanner+"\n\n== Examples\n\n"+examples+"\n")
	}
	// The metadata and description partials are always written, empty when
	// the component has no such content, so a page that includes them keeps
	// building after upstream removes a Metadata section or a description.
	if md := protectCodeSpans(normalizeMetadata(extractMetadata(c.Description))); md != "" {
		w.write(filepath.Join("partials/metadata", typeDir, file), metadataBanner+"\n\n"+md+"\n")
	} else {
		w.write(filepath.Join("partials/metadata", typeDir, file), emptyMetadataPartial)
	}
	plat := w.platforms.get(key, c.Name)
	w.write(filepath.Join("partials/availability", typeDir, file), renderAvailabilityPartial(plat))
	if c.Summary != "" || c.Description != "" || c.Version != "" || c.Status != "" || c.Footnotes != "" {
		w.write(filepath.Join("partials/descriptions", typeDir, file), renderDescriptionPartial(c, typeDir, plat, w.platforms.cloudExcluded))
	} else {
		w.write(filepath.Join("partials/descriptions", typeDir, file), emptyDescriptionPartial)
	}
	w.snippets(key, c)
}

func bloblangNames(specs []bloblangSpec) map[string]bool {
	names := make(map[string]bool, len(specs))
	for _, s := range specs {
		names[s.Name] = true
	}
	return names
}
