inputs:
  label: ""
  mongodb:
    url: "" # No default (required)
    database: "" # No default (required)
    username: ""
    password: ""
    app_name: benthos
    aws:
      enabled: false
      region: "" # No default (optional)
      session_duration: 1h
      id: "" # No default (optional)
      secret: "" # No default (optional)
      token: "" # No default (optional)
      role: "" # No default (optional)
      role_external_id: "" # No default (optional)
      roles: [] # No default (optional)
    collection: "" # No default (required)
    operation: find
    json_marshal_mode: canonical
    query: "" # No default (required)
    auto_replay_nacks: true
    batch_size: "" # No default (optional)
    sort: "" # No default (optional)
    limit: "" # No default (optional)