// Code generated by procgen; DO NOT EDIT.

package notion

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"
	"sync"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/validate"
	"github.com/redpanda-data/benthos/v4/public/bloblang"
	"github.com/redpanda-data/benthos/v4/public/service"

	"github.com/redpanda-data/connect/v4/internal/httpclient"

	v1 "github.com/redpanda-data/connect/v4/procgen/notion/api/v1"
)

// securitySource implements v1.SecuritySource.
type securitySource struct {
	token string
}

func (s *securitySource) BearerAuth(_ context.Context, _ v1.OperationName) (v1.BearerAuth, error) {
	return v1.BearerAuth{Token: s.token}, nil
}

const (
	npFieldAPIKey        = "api_key"
	npFieldNotionVersion = "notion_version"
)

func sharedConfigFields() []*service.ConfigField {
	fields := []*service.ConfigField{
		service.NewStringField(npFieldAPIKey).
			Secret().
			Description("The Notion API integration token."),
		service.NewStringField(npFieldNotionVersion).
			Default("2022-06-28").
			Description("The Notion API version."),
	}
	return append(fields, httpclient.Fields("https://api.notion.com")...)
}

type baseProcessor struct {
	client        *v1.Client
	notionVersion string
	mapping       *bloblang.Executor
	log           *service.Logger
}

func baseProcessorFromParsed(conf *service.ParsedConfig, mgr *service.Resources) (p baseProcessor, err error) {
	p.log = mgr.Logger()

	apiKey, err := conf.FieldString(npFieldAPIKey)
	if err != nil {
		return p, err
	}
	if p.notionVersion, err = conf.FieldString(npFieldNotionVersion); err != nil {
		return p, err
	}

	httpCfg, err := httpclient.NewConfigFromParsed(conf)
	if err != nil {
		return p, err
	}
	httpCfg.MetricPrefix = "notion_http"

	httpClient, err := httpclient.NewClient(httpCfg, mgr)
	if err != nil {
		return p, fmt.Errorf("creating HTTP client: %w", err)
	}

	if p.client, err = v1.NewClient(httpCfg.BaseURL, &securitySource{token: apiKey}, v1.WithClient(httpClient)); err != nil {
		return p, fmt.Errorf("creating Notion client: %w", err)
	}
	if conf.Contains("mapping") {
		if p.mapping, err = conf.FieldBloblang("mapping"); err != nil {
			return p, err
		}
	}

	return p, nil
}

func (p *baseProcessor) Close(context.Context) error { return nil }

// handleAPIError checks for HTTP status errors and sets metadata.
// On HTTP errors, sets status code metadata on the message and returns a
// wrapped error. On other errors, returns a generic request failure.
func handleAPIError(msg *service.Message, err error) error {
	if unexpectedStatus, ok := errors.Into[*validate.UnexpectedStatusCodeError](err); ok {
		msg.MetaSetMut("http_status_code", unexpectedStatus.StatusCode)
		return fmt.Errorf("Notion API error (status %d): %w", unexpectedStatus.StatusCode, err)
	}
	return fmt.Errorf("Notion API request failed: %w", err)
}

// marshalResponse serializes the typed response to JSON and sets it on the message.
func marshalResponse(msg *service.Message, resp any) error {
	b, err := json.Marshal(resp)
	if err != nil {
		return fmt.Errorf("marshaling response: %w", err)
	}
	msg.SetBytes(b)
	return nil
}

// V1BlocksIDChildrenGet processor — get /v1/blocks/{id}/children

func init() {
	service.MustRegisterBatchProcessor(
		"notion_v1_blocks_id_children_get",
		v1BlocksIDChildrenGetConfig(),
		newV1BlocksIDChildrenGetProcessor,
	)
}

func v1BlocksIDChildrenGetConfig() *service.ConfigSpec {
	return service.NewConfigSpec().
		Categories("Services", "Notion").
		Summary("Retrieve block children `GET /v1/blocks/{id}/children`").
		Fields(sharedConfigFields()...).Fields(
		service.NewInterpolatedStringField("id").
			Description(""),
		service.NewInterpolatedStringField("page_size").
			Description("").
			Optional(),
	)
}

type v1BlocksIDChildrenGetProcessor struct {
	baseProcessor
	id       *service.InterpolatedString
	pageSize *service.InterpolatedString
}

func newV1BlocksIDChildrenGetProcessor(conf *service.ParsedConfig, mgr *service.Resources) (service.BatchProcessor, error) {
	base, err := baseProcessorFromParsed(conf, mgr)
	if err != nil {
		return nil, err
	}

	p := &v1BlocksIDChildrenGetProcessor{baseProcessor: base}
	if p.id, err = conf.FieldInterpolatedString("id"); err != nil {
		return nil, err
	}
	if conf.Contains("page_size") {
		if p.pageSize, err = conf.FieldInterpolatedString("page_size"); err != nil {
			return nil, err
		}
	}

	return p, nil
}

func (p *v1BlocksIDChildrenGetProcessor) ProcessBatch(ctx context.Context, batch service.MessageBatch) ([]service.MessageBatch, error) {
	batch = batch.Copy()

	var wg sync.WaitGroup
	wg.Add(len(batch))
	for i := range batch {
		go func(idx int) {
			defer wg.Done()
			if err := p.processV1BlocksIDChildrenGet(ctx, idx, batch); err != nil {
				batch[idx].SetError(err)
			}
		}(i)
	}
	wg.Wait()

	return []service.MessageBatch{batch}, nil
}

func (p *v1BlocksIDChildrenGetProcessor) processV1BlocksIDChildrenGet(ctx context.Context, idx int, batch service.MessageBatch) error {
	msg := batch[idx]
	params := v1.V1BlocksIDChildrenGetParams{
		NotionVersion: v1.NewOptString(p.notionVersion),
	}
	{
		v, err := batch.TryInterpolatedString(idx, p.id)
		if err != nil {
			return fmt.Errorf("interpolating id: %w", err)
		}
		params.ID = v
	}
	if p.pageSize != nil {
		v, err := batch.TryInterpolatedString(idx, p.pageSize)
		if err != nil {
			return fmt.Errorf("interpolating page_size: %w", err)
		}
		intVal, err := strconv.Atoi(v)
		if err != nil {
			return fmt.Errorf("page_size must be integer: %w", err)
		}
		params.PageSize = v1.NewOptInt(intVal)
	}
	res, err := p.client.V1BlocksIDChildrenGet(ctx, params)
	if err != nil {
		return handleAPIError(msg, err)
	}
	return marshalResponse(msg, &res)
}

// V1BlocksIDChildrenPatch processor — patch /v1/blocks/{id}/children

func init() {
	service.MustRegisterBatchProcessor(
		"notion_v1_blocks_id_children_patch",
		v1BlocksIDChildrenPatchConfig(),
		newV1BlocksIDChildrenPatchProcessor,
	)
}

func v1BlocksIDChildrenPatchConfig() *service.ConfigSpec {
	return service.NewConfigSpec().
		Categories("Services", "Notion").
		Summary("Append block children `PATCH /v1/blocks/{id}/children`").
		Fields(sharedConfigFields()...).Fields(
		service.NewBloblangField("mapping").
			Optional().
			Description("An optional xref:guides:bloblang/about.adoc[Bloblang] mapping applied to messages before unmarshaling into the request body."),
		service.NewInterpolatedStringField("id").
			Description(""),
	)
}

type v1BlocksIDChildrenPatchProcessor struct {
	baseProcessor
	id *service.InterpolatedString
}

func newV1BlocksIDChildrenPatchProcessor(conf *service.ParsedConfig, mgr *service.Resources) (service.BatchProcessor, error) {
	base, err := baseProcessorFromParsed(conf, mgr)
	if err != nil {
		return nil, err
	}

	p := &v1BlocksIDChildrenPatchProcessor{baseProcessor: base}
	if p.id, err = conf.FieldInterpolatedString("id"); err != nil {
		return nil, err
	}

	return p, nil
}

func (p *v1BlocksIDChildrenPatchProcessor) ProcessBatch(ctx context.Context, batch service.MessageBatch) ([]service.MessageBatch, error) {
	batch = batch.Copy()

	var wg sync.WaitGroup
	wg.Add(len(batch))
	for i := range batch {
		go func(idx int) {
			defer wg.Done()
			if err := p.processV1BlocksIDChildrenPatch(ctx, idx, batch); err != nil {
				batch[idx].SetError(err)
			}
		}(i)
	}
	wg.Wait()

	return []service.MessageBatch{batch}, nil
}

func (p *v1BlocksIDChildrenPatchProcessor) processV1BlocksIDChildrenPatch(ctx context.Context, idx int, batch service.MessageBatch) error {
	msg := batch[idx]
	params := v1.V1BlocksIDChildrenPatchParams{
		NotionVersion: v1.NewOptString(p.notionVersion),
	}
	{
		v, err := batch.TryInterpolatedString(idx, p.id)
		if err != nil {
			return fmt.Errorf("interpolating id: %w", err)
		}
		params.ID = v
	}
	if p.mapping != nil {
		structured, err := msg.AsStructured()
		if err != nil {
			return fmt.Errorf("parsing message for mapping: %w", err)
		}
		mapped, err := p.mapping.Query(structured)
		if err != nil {
			return fmt.Errorf("executing mapping: %w", err)
		}
		msg.SetStructured(mapped)
	}

	b, err := msg.AsBytes()
	if err != nil {
		return fmt.Errorf("reading message body: %w", err)
	}

	var req v1.AppendBlockChildrenRequest
	if err := req.UnmarshalJSON(b); err != nil {
		return fmt.Errorf("unmarshaling request body: %w", err)
	}
	if err := req.Validate(); err != nil {
		return fmt.Errorf("validating request body: %w", err)
	}

	res, err := p.client.V1BlocksIDChildrenPatch(ctx, &req, params)
	if err != nil {
		return handleAPIError(msg, err)
	}
	return marshalResponse(msg, &res)
}

// V1BlocksIDDelete processor — delete /v1/blocks/{id}

func init() {
	service.MustRegisterBatchProcessor(
		"notion_v1_blocks_id_delete",
		v1BlocksIDDeleteConfig(),
		newV1BlocksIDDeleteProcessor,
	)
}

func v1BlocksIDDeleteConfig() *service.ConfigSpec {
	return service.NewConfigSpec().
		Categories("Services", "Notion").
		Summary("Delete a block `DELETE /v1/blocks/{id}`").
		Fields(sharedConfigFields()...).Fields(
		service.NewInterpolatedStringField("id").
			Description(""),
	)
}

type v1BlocksIDDeleteProcessor struct {
	baseProcessor
	id *service.InterpolatedString
}

func newV1BlocksIDDeleteProcessor(conf *service.ParsedConfig, mgr *service.Resources) (service.BatchProcessor, error) {
	base, err := baseProcessorFromParsed(conf, mgr)
	if err != nil {
		return nil, err
	}

	p := &v1BlocksIDDeleteProcessor{baseProcessor: base}
	if p.id, err = conf.FieldInterpolatedString("id"); err != nil {
		return nil, err
	}

	return p, nil
}

func (p *v1BlocksIDDeleteProcessor) ProcessBatch(ctx context.Context, batch service.MessageBatch) ([]service.MessageBatch, error) {
	batch = batch.Copy()

	var wg sync.WaitGroup
	wg.Add(len(batch))
	for i := range batch {
		go func(idx int) {
			defer wg.Done()
			if err := p.processV1BlocksIDDelete(ctx, idx, batch); err != nil {
				batch[idx].SetError(err)
			}
		}(i)
	}
	wg.Wait()

	return []service.MessageBatch{batch}, nil
}

func (p *v1BlocksIDDeleteProcessor) processV1BlocksIDDelete(ctx context.Context, idx int, batch service.MessageBatch) error {
	msg := batch[idx]
	params := v1.V1BlocksIDDeleteParams{
		NotionVersion: v1.NewOptString(p.notionVersion),
	}
	{
		v, err := batch.TryInterpolatedString(idx, p.id)
		if err != nil {
			return fmt.Errorf("interpolating id: %w", err)
		}
		params.ID = v
	}
	res, err := p.client.V1BlocksIDDelete(ctx, params)
	if err != nil {
		return handleAPIError(msg, err)
	}
	return marshalResponse(msg, &res)
}

// V1BlocksIDGet processor — get /v1/blocks/{id}

func init() {
	service.MustRegisterBatchProcessor(
		"notion_v1_blocks_id_get",
		v1BlocksIDGetConfig(),
		newV1BlocksIDGetProcessor,
	)
}

func v1BlocksIDGetConfig() *service.ConfigSpec {
	return service.NewConfigSpec().
		Categories("Services", "Notion").
		Summary("Retrieve a block `GET /v1/blocks/{id}`").
		Fields(sharedConfigFields()...).Fields(
		service.NewInterpolatedStringField("id").
			Description(""),
	)
}

type v1BlocksIDGetProcessor struct {
	baseProcessor
	id *service.InterpolatedString
}

func newV1BlocksIDGetProcessor(conf *service.ParsedConfig, mgr *service.Resources) (service.BatchProcessor, error) {
	base, err := baseProcessorFromParsed(conf, mgr)
	if err != nil {
		return nil, err
	}

	p := &v1BlocksIDGetProcessor{baseProcessor: base}
	if p.id, err = conf.FieldInterpolatedString("id"); err != nil {
		return nil, err
	}

	return p, nil
}

func (p *v1BlocksIDGetProcessor) ProcessBatch(ctx context.Context, batch service.MessageBatch) ([]service.MessageBatch, error) {
	batch = batch.Copy()

	var wg sync.WaitGroup
	wg.Add(len(batch))
	for i := range batch {
		go func(idx int) {
			defer wg.Done()
			if err := p.processV1BlocksIDGet(ctx, idx, batch); err != nil {
				batch[idx].SetError(err)
			}
		}(i)
	}
	wg.Wait()

	return []service.MessageBatch{batch}, nil
}

func (p *v1BlocksIDGetProcessor) processV1BlocksIDGet(ctx context.Context, idx int, batch service.MessageBatch) error {
	msg := batch[idx]
	params := v1.V1BlocksIDGetParams{
		NotionVersion: v1.NewOptString(p.notionVersion),
	}
	{
		v, err := batch.TryInterpolatedString(idx, p.id)
		if err != nil {
			return fmt.Errorf("interpolating id: %w", err)
		}
		params.ID = v
	}
	res, err := p.client.V1BlocksIDGet(ctx, params)
	if err != nil {
		return handleAPIError(msg, err)
	}
	return marshalResponse(msg, &res)
}

// V1BlocksIDPatch processor — patch /v1/blocks/{id}

func init() {
	service.MustRegisterBatchProcessor(
		"notion_v1_blocks_id_patch",
		v1BlocksIDPatchConfig(),
		newV1BlocksIDPatchProcessor,
	)
}

func v1BlocksIDPatchConfig() *service.ConfigSpec {
	return service.NewConfigSpec().
		Categories("Services", "Notion").
		Summary("Update a block `PATCH /v1/blocks/{id}`").
		Description("This endpoint allows you to update block content. [See Full Documentation](https://developers.notion.com/reference/update-a-block)").
		Fields(sharedConfigFields()...).Fields(
		service.NewBloblangField("mapping").
			Optional().
			Description("An optional xref:guides:bloblang/about.adoc[Bloblang] mapping applied to messages before unmarshaling into the request body."),
		service.NewInterpolatedStringField("id").
			Description(""),
	)
}

type v1BlocksIDPatchProcessor struct {
	baseProcessor
	id *service.InterpolatedString
}

func newV1BlocksIDPatchProcessor(conf *service.ParsedConfig, mgr *service.Resources) (service.BatchProcessor, error) {
	base, err := baseProcessorFromParsed(conf, mgr)
	if err != nil {
		return nil, err
	}

	p := &v1BlocksIDPatchProcessor{baseProcessor: base}
	if p.id, err = conf.FieldInterpolatedString("id"); err != nil {
		return nil, err
	}

	return p, nil
}

func (p *v1BlocksIDPatchProcessor) ProcessBatch(ctx context.Context, batch service.MessageBatch) ([]service.MessageBatch, error) {
	batch = batch.Copy()

	var wg sync.WaitGroup
	wg.Add(len(batch))
	for i := range batch {
		go func(idx int) {
			defer wg.Done()
			if err := p.processV1BlocksIDPatch(ctx, idx, batch); err != nil {
				batch[idx].SetError(err)
			}
		}(i)
	}
	wg.Wait()

	return []service.MessageBatch{batch}, nil
}

func (p *v1BlocksIDPatchProcessor) processV1BlocksIDPatch(ctx context.Context, idx int, batch service.MessageBatch) error {
	msg := batch[idx]
	params := v1.V1BlocksIDPatchParams{
		NotionVersion: v1.NewOptString(p.notionVersion),
	}
	{
		v, err := batch.TryInterpolatedString(idx, p.id)
		if err != nil {
			return fmt.Errorf("interpolating id: %w", err)
		}
		params.ID = v
	}
	if p.mapping != nil {
		structured, err := msg.AsStructured()
		if err != nil {
			return fmt.Errorf("parsing message for mapping: %w", err)
		}
		mapped, err := p.mapping.Query(structured)
		if err != nil {
			return fmt.Errorf("executing mapping: %w", err)
		}
		msg.SetStructured(mapped)
	}

	b, err := msg.AsBytes()
	if err != nil {
		return fmt.Errorf("reading message body: %w", err)
	}

	var req v1.UpdateBlockRequest
	if err := req.UnmarshalJSON(b); err != nil {
		return fmt.Errorf("unmarshaling request body: %w", err)
	}
	if err := req.Validate(); err != nil {
		return fmt.Errorf("validating request body: %w", err)
	}

	res, err := p.client.V1BlocksIDPatch(ctx, &req, params)
	if err != nil {
		return handleAPIError(msg, err)
	}
	return marshalResponse(msg, &res)
}

// V1CommentsGet processor — get /v1/comments

func init() {
	service.MustRegisterBatchProcessor(
		"notion_v1_comments_get",
		v1CommentsGetConfig(),
		newV1CommentsGetProcessor,
	)
}

func v1CommentsGetConfig() *service.ConfigSpec {
	return service.NewConfigSpec().
		Categories("Services", "Notion").
		Summary("Retrieve comments `GET /v1/comments`").
		Description("Retrieve a user object using the ID specified in the request path.").
		Fields(sharedConfigFields()...).Fields(
		service.NewInterpolatedStringField("block_id").
			Description("").
			Optional(),
		service.NewInterpolatedStringField("page_size").
			Description("").
			Optional(),
	)
}

type v1CommentsGetProcessor struct {
	baseProcessor
	blockID  *service.InterpolatedString
	pageSize *service.InterpolatedString
}

func newV1CommentsGetProcessor(conf *service.ParsedConfig, mgr *service.Resources) (service.BatchProcessor, error) {
	base, err := baseProcessorFromParsed(conf, mgr)
	if err != nil {
		return nil, err
	}

	p := &v1CommentsGetProcessor{baseProcessor: base}
	if conf.Contains("block_id") {
		if p.blockID, err = conf.FieldInterpolatedString("block_id"); err != nil {
			return nil, err
		}
	}
	if conf.Contains("page_size") {
		if p.pageSize, err = conf.FieldInterpolatedString("page_size"); err != nil {
			return nil, err
		}
	}

	return p, nil
}

func (p *v1CommentsGetProcessor) ProcessBatch(ctx context.Context, batch service.MessageBatch) ([]service.MessageBatch, error) {
	batch = batch.Copy()

	var wg sync.WaitGroup
	wg.Add(len(batch))
	for i := range batch {
		go func(idx int) {
			defer wg.Done()
			if err := p.processV1CommentsGet(ctx, idx, batch); err != nil {
				batch[idx].SetError(err)
			}
		}(i)
	}
	wg.Wait()

	return []service.MessageBatch{batch}, nil
}

func (p *v1CommentsGetProcessor) processV1CommentsGet(ctx context.Context, idx int, batch service.MessageBatch) error {
	msg := batch[idx]
	params := v1.V1CommentsGetParams{
		NotionVersion: v1.NewOptString(p.notionVersion),
	}
	if p.blockID != nil {
		v, err := batch.TryInterpolatedString(idx, p.blockID)
		if err != nil {
			return fmt.Errorf("interpolating block_id: %w", err)
		}
		params.BlockID = v1.NewOptString(v)
	}
	if p.pageSize != nil {
		v, err := batch.TryInterpolatedString(idx, p.pageSize)
		if err != nil {
			return fmt.Errorf("interpolating page_size: %w", err)
		}
		intVal, err := strconv.Atoi(v)
		if err != nil {
			return fmt.Errorf("page_size must be integer: %w", err)
		}
		params.PageSize = v1.NewOptInt(intVal)
	}
	res, err := p.client.V1CommentsGet(ctx, params)
	if err != nil {
		return handleAPIError(msg, err)
	}
	return marshalResponse(msg, &res)
}

// V1CommentsPost processor — post /v1/comments

func init() {
	service.MustRegisterBatchProcessor(
		"notion_v1_comments_post",
		v1CommentsPostConfig(),
		newV1CommentsPostProcessor,
	)
}

func v1CommentsPostConfig() *service.ConfigSpec {
	return service.NewConfigSpec().
		Categories("Services", "Notion").
		Summary("Add comment to discussion `POST /v1/comments`").
		Fields(sharedConfigFields()...).Fields(
		service.NewBloblangField("mapping").
			Optional().
			Description("An optional xref:guides:bloblang/about.adoc[Bloblang] mapping applied to messages before unmarshaling into the request body."),
	)
}

type v1CommentsPostProcessor struct {
	baseProcessor
}

func newV1CommentsPostProcessor(conf *service.ParsedConfig, mgr *service.Resources) (service.BatchProcessor, error) {
	base, err := baseProcessorFromParsed(conf, mgr)
	if err != nil {
		return nil, err
	}

	p := &v1CommentsPostProcessor{baseProcessor: base}

	return p, nil
}

func (p *v1CommentsPostProcessor) ProcessBatch(ctx context.Context, batch service.MessageBatch) ([]service.MessageBatch, error) {
	batch = batch.Copy()

	var wg sync.WaitGroup
	wg.Add(len(batch))
	for i := range batch {
		go func(idx int) {
			defer wg.Done()
			if err := p.processV1CommentsPost(ctx, idx, batch); err != nil {
				batch[idx].SetError(err)
			}
		}(i)
	}
	wg.Wait()

	return []service.MessageBatch{batch}, nil
}

func (p *v1CommentsPostProcessor) processV1CommentsPost(ctx context.Context, idx int, batch service.MessageBatch) error {
	msg := batch[idx]
	params := v1.V1CommentsPostParams{
		NotionVersion: v1.NewOptString(p.notionVersion),
	}
	if p.mapping != nil {
		structured, err := msg.AsStructured()
		if err != nil {
			return fmt.Errorf("parsing message for mapping: %w", err)
		}
		mapped, err := p.mapping.Query(structured)
		if err != nil {
			return fmt.Errorf("executing mapping: %w", err)
		}
		msg.SetStructured(mapped)
	}

	b, err := msg.AsBytes()
	if err != nil {
		return fmt.Errorf("reading message body: %w", err)
	}

	var req v1.CreateCommentRequest
	if err := req.UnmarshalJSON(b); err != nil {
		return fmt.Errorf("unmarshaling request body: %w", err)
	}
	if err := req.Validate(); err != nil {
		return fmt.Errorf("validating request body: %w", err)
	}

	res, err := p.client.V1CommentsPost(ctx, &req, params)
	if err != nil {
		return handleAPIError(msg, err)
	}
	return marshalResponse(msg, &res)
}

// V1DatabasesIDGet processor — get /v1/databases/{id}

func init() {
	service.MustRegisterBatchProcessor(
		"notion_v1_databases_id_get",
		v1DatabasesIDGetConfig(),
		newV1DatabasesIDGetProcessor,
	)
}

func v1DatabasesIDGetConfig() *service.ConfigSpec {
	return service.NewConfigSpec().
		Categories("Services", "Notion").
		Summary("Retrieve a database `GET /v1/databases/{id}`").
		Description("Retrieves a database object using the ID specified in the request path. ").
		Fields(sharedConfigFields()...).Fields(
		service.NewInterpolatedStringField("id").
			Description(""),
	)
}

type v1DatabasesIDGetProcessor struct {
	baseProcessor
	id *service.InterpolatedString
}

func newV1DatabasesIDGetProcessor(conf *service.ParsedConfig, mgr *service.Resources) (service.BatchProcessor, error) {
	base, err := baseProcessorFromParsed(conf, mgr)
	if err != nil {
		return nil, err
	}

	p := &v1DatabasesIDGetProcessor{baseProcessor: base}
	if p.id, err = conf.FieldInterpolatedString("id"); err != nil {
		return nil, err
	}

	return p, nil
}

func (p *v1DatabasesIDGetProcessor) ProcessBatch(ctx context.Context, batch service.MessageBatch) ([]service.MessageBatch, error) {
	batch = batch.Copy()

	var wg sync.WaitGroup
	wg.Add(len(batch))
	for i := range batch {
		go func(idx int) {
			defer wg.Done()
			if err := p.processV1DatabasesIDGet(ctx, idx, batch); err != nil {
				batch[idx].SetError(err)
			}
		}(i)
	}
	wg.Wait()

	return []service.MessageBatch{batch}, nil
}

func (p *v1DatabasesIDGetProcessor) processV1DatabasesIDGet(ctx context.Context, idx int, batch service.MessageBatch) error {
	msg := batch[idx]
	params := v1.V1DatabasesIDGetParams{
		NotionVersion: v1.NewOptString(p.notionVersion),
	}
	{
		v, err := batch.TryInterpolatedString(idx, p.id)
		if err != nil {
			return fmt.Errorf("interpolating id: %w", err)
		}
		params.ID = v
	}
	res, err := p.client.V1DatabasesIDGet(ctx, params)
	if err != nil {
		return handleAPIError(msg, err)
	}
	return marshalResponse(msg, &res)
}

// V1DatabasesIDPatch processor — patch /v1/databases/{id}

func init() {
	service.MustRegisterBatchProcessor(
		"notion_v1_databases_id_patch",
		v1DatabasesIDPatchConfig(),
		newV1DatabasesIDPatchProcessor,
	)
}

func v1DatabasesIDPatchConfig() *service.ConfigSpec {
	return service.NewConfigSpec().
		Categories("Services", "Notion").
		Summary("Update database properties `PATCH /v1/databases/{id}`").
		Fields(sharedConfigFields()...).Fields(
		service.NewBloblangField("mapping").
			Optional().
			Description("An optional xref:guides:bloblang/about.adoc[Bloblang] mapping applied to messages before unmarshaling into the request body."),
		service.NewInterpolatedStringField("id").
			Description(""),
	)
}

type v1DatabasesIDPatchProcessor struct {
	baseProcessor
	id *service.InterpolatedString
}

func newV1DatabasesIDPatchProcessor(conf *service.ParsedConfig, mgr *service.Resources) (service.BatchProcessor, error) {
	base, err := baseProcessorFromParsed(conf, mgr)
	if err != nil {
		return nil, err
	}

	p := &v1DatabasesIDPatchProcessor{baseProcessor: base}
	if p.id, err = conf.FieldInterpolatedString("id"); err != nil {
		return nil, err
	}

	return p, nil
}

func (p *v1DatabasesIDPatchProcessor) ProcessBatch(ctx context.Context, batch service.MessageBatch) ([]service.MessageBatch, error) {
	batch = batch.Copy()

	var wg sync.WaitGroup
	wg.Add(len(batch))
	for i := range batch {
		go func(idx int) {
			defer wg.Done()
			if err := p.processV1DatabasesIDPatch(ctx, idx, batch); err != nil {
				batch[idx].SetError(err)
			}
		}(i)
	}
	wg.Wait()

	return []service.MessageBatch{batch}, nil
}

func (p *v1DatabasesIDPatchProcessor) processV1DatabasesIDPatch(ctx context.Context, idx int, batch service.MessageBatch) error {
	msg := batch[idx]
	params := v1.V1DatabasesIDPatchParams{
		NotionVersion: v1.NewOptString(p.notionVersion),
	}
	{
		v, err := batch.TryInterpolatedString(idx, p.id)
		if err != nil {
			return fmt.Errorf("interpolating id: %w", err)
		}
		params.ID = v
	}
	if p.mapping != nil {
		structured, err := msg.AsStructured()
		if err != nil {
			return fmt.Errorf("parsing message for mapping: %w", err)
		}
		mapped, err := p.mapping.Query(structured)
		if err != nil {
			return fmt.Errorf("executing mapping: %w", err)
		}
		msg.SetStructured(mapped)
	}

	b, err := msg.AsBytes()
	if err != nil {
		return fmt.Errorf("reading message body: %w", err)
	}

	var req v1.UpdateDatabaseRequest
	if err := req.UnmarshalJSON(b); err != nil {
		return fmt.Errorf("unmarshaling request body: %w", err)
	}
	if err := req.Validate(); err != nil {
		return fmt.Errorf("validating request body: %w", err)
	}

	res, err := p.client.V1DatabasesIDPatch(ctx, &req, params)
	if err != nil {
		return handleAPIError(msg, err)
	}
	return marshalResponse(msg, &res)
}

// V1DatabasesIDQueryPost processor — post /v1/databases/{id}/query

func init() {
	service.MustRegisterBatchProcessor(
		"notion_v1_databases_id_query_post",
		v1DatabasesIDQueryPostConfig(),
		newV1DatabasesIDQueryPostProcessor,
	)
}

func v1DatabasesIDQueryPostConfig() *service.ConfigSpec {
	return service.NewConfigSpec().
		Categories("Services", "Notion").
		Summary("Filter a database `POST /v1/databases/{id}/query`").
		Fields(sharedConfigFields()...).Fields(
		service.NewBloblangField("mapping").
			Optional().
			Description("An optional xref:guides:bloblang/about.adoc[Bloblang] mapping applied to messages before unmarshaling into the request body."),
		service.NewInterpolatedStringField("id").
			Description(""),
	)
}

type v1DatabasesIDQueryPostProcessor struct {
	baseProcessor
	id *service.InterpolatedString
}

func newV1DatabasesIDQueryPostProcessor(conf *service.ParsedConfig, mgr *service.Resources) (service.BatchProcessor, error) {
	base, err := baseProcessorFromParsed(conf, mgr)
	if err != nil {
		return nil, err
	}

	p := &v1DatabasesIDQueryPostProcessor{baseProcessor: base}
	if p.id, err = conf.FieldInterpolatedString("id"); err != nil {
		return nil, err
	}

	return p, nil
}

func (p *v1DatabasesIDQueryPostProcessor) ProcessBatch(ctx context.Context, batch service.MessageBatch) ([]service.MessageBatch, error) {
	batch = batch.Copy()

	var wg sync.WaitGroup
	wg.Add(len(batch))
	for i := range batch {
		go func(idx int) {
			defer wg.Done()
			if err := p.processV1DatabasesIDQueryPost(ctx, idx, batch); err != nil {
				batch[idx].SetError(err)
			}
		}(i)
	}
	wg.Wait()

	return []service.MessageBatch{batch}, nil
}

func (p *v1DatabasesIDQueryPostProcessor) processV1DatabasesIDQueryPost(ctx context.Context, idx int, batch service.MessageBatch) error {
	msg := batch[idx]
	params := v1.V1DatabasesIDQueryPostParams{
		NotionVersion: v1.NewOptString(p.notionVersion),
	}
	{
		v, err := batch.TryInterpolatedString(idx, p.id)
		if err != nil {
			return fmt.Errorf("interpolating id: %w", err)
		}
		params.ID = v
	}
	if p.mapping != nil {
		structured, err := msg.AsStructured()
		if err != nil {
			return fmt.Errorf("parsing message for mapping: %w", err)
		}
		mapped, err := p.mapping.Query(structured)
		if err != nil {
			return fmt.Errorf("executing mapping: %w", err)
		}
		msg.SetStructured(mapped)
	}

	b, err := msg.AsBytes()
	if err != nil {
		return fmt.Errorf("reading message body: %w", err)
	}

	var req v1.QueryDataSourceRequest
	if err := req.UnmarshalJSON(b); err != nil {
		return fmt.Errorf("unmarshaling request body: %w", err)
	}
	if err := req.Validate(); err != nil {
		return fmt.Errorf("validating request body: %w", err)
	}

	res, err := p.client.V1DatabasesIDQueryPost(ctx, &req, params)
	if err != nil {
		return handleAPIError(msg, err)
	}
	return marshalResponse(msg, &res)
}

// V1DatabasesPost processor — post /v1/databases/

func init() {
	service.MustRegisterBatchProcessor(
		"notion_v1_databases_post",
		v1DatabasesPostConfig(),
		newV1DatabasesPostProcessor,
	)
}

func v1DatabasesPostConfig() *service.ConfigSpec {
	return service.NewConfigSpec().
		Categories("Services", "Notion").
		Summary("Create a database `POST /v1/databases/`").
		Fields(sharedConfigFields()...).Fields(
		service.NewBloblangField("mapping").
			Optional().
			Description("An optional xref:guides:bloblang/about.adoc[Bloblang] mapping applied to messages before unmarshaling into the request body."),
	)
}

type v1DatabasesPostProcessor struct {
	baseProcessor
}

func newV1DatabasesPostProcessor(conf *service.ParsedConfig, mgr *service.Resources) (service.BatchProcessor, error) {
	base, err := baseProcessorFromParsed(conf, mgr)
	if err != nil {
		return nil, err
	}

	p := &v1DatabasesPostProcessor{baseProcessor: base}

	return p, nil
}

func (p *v1DatabasesPostProcessor) ProcessBatch(ctx context.Context, batch service.MessageBatch) ([]service.MessageBatch, error) {
	batch = batch.Copy()

	var wg sync.WaitGroup
	wg.Add(len(batch))
	for i := range batch {
		go func(idx int) {
			defer wg.Done()
			if err := p.processV1DatabasesPost(ctx, idx, batch); err != nil {
				batch[idx].SetError(err)
			}
		}(i)
	}
	wg.Wait()

	return []service.MessageBatch{batch}, nil
}

func (p *v1DatabasesPostProcessor) processV1DatabasesPost(ctx context.Context, idx int, batch service.MessageBatch) error {
	msg := batch[idx]
	params := v1.V1DatabasesPostParams{
		NotionVersion: v1.NewOptString(p.notionVersion),
	}
	if p.mapping != nil {
		structured, err := msg.AsStructured()
		if err != nil {
			return fmt.Errorf("parsing message for mapping: %w", err)
		}
		mapped, err := p.mapping.Query(structured)
		if err != nil {
			return fmt.Errorf("executing mapping: %w", err)
		}
		msg.SetStructured(mapped)
	}

	b, err := msg.AsBytes()
	if err != nil {
		return fmt.Errorf("reading message body: %w", err)
	}

	var req v1.CreateDatabaseRequest
	if err := req.UnmarshalJSON(b); err != nil {
		return fmt.Errorf("unmarshaling request body: %w", err)
	}
	if err := req.Validate(); err != nil {
		return fmt.Errorf("validating request body: %w", err)
	}

	res, err := p.client.V1DatabasesPost(ctx, &req, params)
	if err != nil {
		return handleAPIError(msg, err)
	}
	return marshalResponse(msg, &res)
}

// V1PagesIDGet processor — get /v1/pages/{id}

func init() {
	service.MustRegisterBatchProcessor(
		"notion_v1_pages_id_get",
		v1PagesIDGetConfig(),
		newV1PagesIDGetProcessor,
	)
}

func v1PagesIDGetConfig() *service.ConfigSpec {
	return service.NewConfigSpec().
		Categories("Services", "Notion").
		Summary("Retrieve a page `GET /v1/pages/{id}`").
		Description("Retrieves a Page object using the ID in the request path. This endpoint exposes page properties, not page content. ").
		Fields(sharedConfigFields()...).Fields(
		service.NewInterpolatedStringField("id").
			Description(""),
	)
}

type v1PagesIDGetProcessor struct {
	baseProcessor
	id *service.InterpolatedString
}

func newV1PagesIDGetProcessor(conf *service.ParsedConfig, mgr *service.Resources) (service.BatchProcessor, error) {
	base, err := baseProcessorFromParsed(conf, mgr)
	if err != nil {
		return nil, err
	}

	p := &v1PagesIDGetProcessor{baseProcessor: base}
	if p.id, err = conf.FieldInterpolatedString("id"); err != nil {
		return nil, err
	}

	return p, nil
}

func (p *v1PagesIDGetProcessor) ProcessBatch(ctx context.Context, batch service.MessageBatch) ([]service.MessageBatch, error) {
	batch = batch.Copy()

	var wg sync.WaitGroup
	wg.Add(len(batch))
	for i := range batch {
		go func(idx int) {
			defer wg.Done()
			if err := p.processV1PagesIDGet(ctx, idx, batch); err != nil {
				batch[idx].SetError(err)
			}
		}(i)
	}
	wg.Wait()

	return []service.MessageBatch{batch}, nil
}

func (p *v1PagesIDGetProcessor) processV1PagesIDGet(ctx context.Context, idx int, batch service.MessageBatch) error {
	msg := batch[idx]
	params := v1.V1PagesIDGetParams{
		NotionVersion: v1.NewOptString(p.notionVersion),
	}
	{
		v, err := batch.TryInterpolatedString(idx, p.id)
		if err != nil {
			return fmt.Errorf("interpolating id: %w", err)
		}
		params.ID = v
	}
	res, err := p.client.V1PagesIDGet(ctx, params)
	if err != nil {
		return handleAPIError(msg, err)
	}
	return marshalResponse(msg, &res)
}

// V1PagesIDPatch processor — patch /v1/pages/{id}

func init() {
	service.MustRegisterBatchProcessor(
		"notion_v1_pages_id_patch",
		v1PagesIDPatchConfig(),
		newV1PagesIDPatchProcessor,
	)
}

func v1PagesIDPatchConfig() *service.ConfigSpec {
	return service.NewConfigSpec().
		Categories("Services", "Notion").
		Summary("Archive a page `PATCH /v1/pages/{id}`").
		Fields(sharedConfigFields()...).Fields(
		service.NewBloblangField("mapping").
			Optional().
			Description("An optional xref:guides:bloblang/about.adoc[Bloblang] mapping applied to messages before unmarshaling into the request body."),
		service.NewInterpolatedStringField("id").
			Description(""),
	)
}

type v1PagesIDPatchProcessor struct {
	baseProcessor
	id *service.InterpolatedString
}

func newV1PagesIDPatchProcessor(conf *service.ParsedConfig, mgr *service.Resources) (service.BatchProcessor, error) {
	base, err := baseProcessorFromParsed(conf, mgr)
	if err != nil {
		return nil, err
	}

	p := &v1PagesIDPatchProcessor{baseProcessor: base}
	if p.id, err = conf.FieldInterpolatedString("id"); err != nil {
		return nil, err
	}

	return p, nil
}

func (p *v1PagesIDPatchProcessor) ProcessBatch(ctx context.Context, batch service.MessageBatch) ([]service.MessageBatch, error) {
	batch = batch.Copy()

	var wg sync.WaitGroup
	wg.Add(len(batch))
	for i := range batch {
		go func(idx int) {
			defer wg.Done()
			if err := p.processV1PagesIDPatch(ctx, idx, batch); err != nil {
				batch[idx].SetError(err)
			}
		}(i)
	}
	wg.Wait()

	return []service.MessageBatch{batch}, nil
}

func (p *v1PagesIDPatchProcessor) processV1PagesIDPatch(ctx context.Context, idx int, batch service.MessageBatch) error {
	msg := batch[idx]
	params := v1.V1PagesIDPatchParams{
		NotionVersion: v1.NewOptString(p.notionVersion),
	}
	{
		v, err := batch.TryInterpolatedString(idx, p.id)
		if err != nil {
			return fmt.Errorf("interpolating id: %w", err)
		}
		params.ID = v
	}
	if p.mapping != nil {
		structured, err := msg.AsStructured()
		if err != nil {
			return fmt.Errorf("parsing message for mapping: %w", err)
		}
		mapped, err := p.mapping.Query(structured)
		if err != nil {
			return fmt.Errorf("executing mapping: %w", err)
		}
		msg.SetStructured(mapped)
	}

	b, err := msg.AsBytes()
	if err != nil {
		return fmt.Errorf("reading message body: %w", err)
	}

	var req v1.UpdatePageRequest
	if err := req.UnmarshalJSON(b); err != nil {
		return fmt.Errorf("unmarshaling request body: %w", err)
	}
	if err := req.Validate(); err != nil {
		return fmt.Errorf("validating request body: %w", err)
	}

	res, err := p.client.V1PagesIDPatch(ctx, &req, params)
	if err != nil {
		return handleAPIError(msg, err)
	}
	return marshalResponse(msg, &res)
}

// V1PagesPageIDPropertiesPropertyIDGet processor — get /v1/pages/{page_id}/properties/{property_id}

func init() {
	service.MustRegisterBatchProcessor(
		"notion_v1_pages_page_id_properties_property_id_get",
		v1PagesPageIDPropertiesPropertyIDGetConfig(),
		newV1PagesPageIDPropertiesPropertyIDGetProcessor,
	)
}

func v1PagesPageIDPropertiesPropertyIDGetConfig() *service.ConfigSpec {
	return service.NewConfigSpec().
		Categories("Services", "Notion").
		Summary("Retrieve a page property item `GET /v1/pages/{page_id}/properties/{property_id}`").
		Fields(sharedConfigFields()...).Fields(
		service.NewInterpolatedStringField("page_id").
			Description(""),
		service.NewInterpolatedStringField("property_id").
			Description(""),
	)
}

type v1PagesPageIDPropertiesPropertyIDGetProcessor struct {
	baseProcessor
	pageID     *service.InterpolatedString
	propertyID *service.InterpolatedString
}

func newV1PagesPageIDPropertiesPropertyIDGetProcessor(conf *service.ParsedConfig, mgr *service.Resources) (service.BatchProcessor, error) {
	base, err := baseProcessorFromParsed(conf, mgr)
	if err != nil {
		return nil, err
	}

	p := &v1PagesPageIDPropertiesPropertyIDGetProcessor{baseProcessor: base}
	if p.pageID, err = conf.FieldInterpolatedString("page_id"); err != nil {
		return nil, err
	}
	if p.propertyID, err = conf.FieldInterpolatedString("property_id"); err != nil {
		return nil, err
	}

	return p, nil
}

func (p *v1PagesPageIDPropertiesPropertyIDGetProcessor) ProcessBatch(ctx context.Context, batch service.MessageBatch) ([]service.MessageBatch, error) {
	batch = batch.Copy()

	var wg sync.WaitGroup
	wg.Add(len(batch))
	for i := range batch {
		go func(idx int) {
			defer wg.Done()
			if err := p.processV1PagesPageIDPropertiesPropertyIDGet(ctx, idx, batch); err != nil {
				batch[idx].SetError(err)
			}
		}(i)
	}
	wg.Wait()

	return []service.MessageBatch{batch}, nil
}

func (p *v1PagesPageIDPropertiesPropertyIDGetProcessor) processV1PagesPageIDPropertiesPropertyIDGet(ctx context.Context, idx int, batch service.MessageBatch) error {
	msg := batch[idx]
	params := v1.V1PagesPageIDPropertiesPropertyIDGetParams{
		NotionVersion: v1.NewOptString(p.notionVersion),
	}
	{
		v, err := batch.TryInterpolatedString(idx, p.pageID)
		if err != nil {
			return fmt.Errorf("interpolating page_id: %w", err)
		}
		params.PageID = v
	}
	{
		v, err := batch.TryInterpolatedString(idx, p.propertyID)
		if err != nil {
			return fmt.Errorf("interpolating property_id: %w", err)
		}
		params.PropertyID = v
	}
	res, err := p.client.V1PagesPageIDPropertiesPropertyIDGet(ctx, params)
	if err != nil {
		return handleAPIError(msg, err)
	}
	return marshalResponse(msg, &res)
}

// V1PagesPost processor — post /v1/pages/

func init() {
	service.MustRegisterBatchProcessor(
		"notion_v1_pages_post",
		v1PagesPostConfig(),
		newV1PagesPostProcessor,
	)
}

func v1PagesPostConfig() *service.ConfigSpec {
	return service.NewConfigSpec().
		Categories("Services", "Notion").
		Summary("Create a page with content `POST /v1/pages/`").
		Fields(sharedConfigFields()...).Fields(
		service.NewBloblangField("mapping").
			Optional().
			Description("An optional xref:guides:bloblang/about.adoc[Bloblang] mapping applied to messages before unmarshaling into the request body."),
	)
}

type v1PagesPostProcessor struct {
	baseProcessor
}

func newV1PagesPostProcessor(conf *service.ParsedConfig, mgr *service.Resources) (service.BatchProcessor, error) {
	base, err := baseProcessorFromParsed(conf, mgr)
	if err != nil {
		return nil, err
	}

	p := &v1PagesPostProcessor{baseProcessor: base}

	return p, nil
}

func (p *v1PagesPostProcessor) ProcessBatch(ctx context.Context, batch service.MessageBatch) ([]service.MessageBatch, error) {
	batch = batch.Copy()

	var wg sync.WaitGroup
	wg.Add(len(batch))
	for i := range batch {
		go func(idx int) {
			defer wg.Done()
			if err := p.processV1PagesPost(ctx, idx, batch); err != nil {
				batch[idx].SetError(err)
			}
		}(i)
	}
	wg.Wait()

	return []service.MessageBatch{batch}, nil
}

func (p *v1PagesPostProcessor) processV1PagesPost(ctx context.Context, idx int, batch service.MessageBatch) error {
	msg := batch[idx]
	params := v1.V1PagesPostParams{
		NotionVersion: v1.NewOptString(p.notionVersion),
	}
	if p.mapping != nil {
		structured, err := msg.AsStructured()
		if err != nil {
			return fmt.Errorf("parsing message for mapping: %w", err)
		}
		mapped, err := p.mapping.Query(structured)
		if err != nil {
			return fmt.Errorf("executing mapping: %w", err)
		}
		msg.SetStructured(mapped)
	}

	b, err := msg.AsBytes()
	if err != nil {
		return fmt.Errorf("reading message body: %w", err)
	}

	var req v1.CreatePageRequest
	if err := req.UnmarshalJSON(b); err != nil {
		return fmt.Errorf("unmarshaling request body: %w", err)
	}
	if err := req.Validate(); err != nil {
		return fmt.Errorf("validating request body: %w", err)
	}

	res, err := p.client.V1PagesPost(ctx, &req, params)
	if err != nil {
		return handleAPIError(msg, err)
	}
	return marshalResponse(msg, &res)
}

// V1SearchPost processor — post /v1/search

func init() {
	service.MustRegisterBatchProcessor(
		"notion_v1_search_post",
		v1SearchPostConfig(),
		newV1SearchPostProcessor,
	)
}

func v1SearchPostConfig() *service.ConfigSpec {
	return service.NewConfigSpec().
		Categories("Services", "Notion").
		Summary("Search `POST /v1/search`").
		Fields(sharedConfigFields()...).Fields(
		service.NewBloblangField("mapping").
			Optional().
			Description("An optional xref:guides:bloblang/about.adoc[Bloblang] mapping applied to messages before unmarshaling into the request body."),
	)
}

type v1SearchPostProcessor struct {
	baseProcessor
}

func newV1SearchPostProcessor(conf *service.ParsedConfig, mgr *service.Resources) (service.BatchProcessor, error) {
	base, err := baseProcessorFromParsed(conf, mgr)
	if err != nil {
		return nil, err
	}

	p := &v1SearchPostProcessor{baseProcessor: base}

	return p, nil
}

func (p *v1SearchPostProcessor) ProcessBatch(ctx context.Context, batch service.MessageBatch) ([]service.MessageBatch, error) {
	batch = batch.Copy()

	var wg sync.WaitGroup
	wg.Add(len(batch))
	for i := range batch {
		go func(idx int) {
			defer wg.Done()
			if err := p.processV1SearchPost(ctx, idx, batch); err != nil {
				batch[idx].SetError(err)
			}
		}(i)
	}
	wg.Wait()

	return []service.MessageBatch{batch}, nil
}

func (p *v1SearchPostProcessor) processV1SearchPost(ctx context.Context, idx int, batch service.MessageBatch) error {
	msg := batch[idx]
	params := v1.V1SearchPostParams{
		NotionVersion: v1.NewOptString(p.notionVersion),
	}
	if p.mapping != nil {
		structured, err := msg.AsStructured()
		if err != nil {
			return fmt.Errorf("parsing message for mapping: %w", err)
		}
		mapped, err := p.mapping.Query(structured)
		if err != nil {
			return fmt.Errorf("executing mapping: %w", err)
		}
		msg.SetStructured(mapped)
	}

	b, err := msg.AsBytes()
	if err != nil {
		return fmt.Errorf("reading message body: %w", err)
	}

	var req v1.SearchRequest
	if err := req.UnmarshalJSON(b); err != nil {
		return fmt.Errorf("unmarshaling request body: %w", err)
	}
	if err := req.Validate(); err != nil {
		return fmt.Errorf("validating request body: %w", err)
	}

	res, err := p.client.V1SearchPost(ctx, &req, params)
	if err != nil {
		return handleAPIError(msg, err)
	}
	return marshalResponse(msg, &res)
}

// V1UsersGet processor — get /v1/users

func init() {
	service.MustRegisterBatchProcessor(
		"notion_v1_users_get",
		v1UsersGetConfig(),
		newV1UsersGetProcessor,
	)
}

func v1UsersGetConfig() *service.ConfigSpec {
	return service.NewConfigSpec().
		Categories("Services", "Notion").
		Summary("List all users `GET /v1/users`").
		Description("Returns a paginated list of user objects for a workspace").
		Fields(sharedConfigFields()...).Fields()
}

type v1UsersGetProcessor struct {
	baseProcessor
}

func newV1UsersGetProcessor(conf *service.ParsedConfig, mgr *service.Resources) (service.BatchProcessor, error) {
	base, err := baseProcessorFromParsed(conf, mgr)
	if err != nil {
		return nil, err
	}

	p := &v1UsersGetProcessor{baseProcessor: base}

	return p, nil
}

func (p *v1UsersGetProcessor) ProcessBatch(ctx context.Context, batch service.MessageBatch) ([]service.MessageBatch, error) {
	batch = batch.Copy()

	var wg sync.WaitGroup
	wg.Add(len(batch))
	for i := range batch {
		go func(idx int) {
			defer wg.Done()
			if err := p.processV1UsersGet(ctx, idx, batch); err != nil {
				batch[idx].SetError(err)
			}
		}(i)
	}
	wg.Wait()

	return []service.MessageBatch{batch}, nil
}

func (p *v1UsersGetProcessor) processV1UsersGet(ctx context.Context, idx int, batch service.MessageBatch) error {
	msg := batch[idx]
	params := v1.V1UsersGetParams{
		NotionVersion: v1.NewOptString(p.notionVersion),
	}
	res, err := p.client.V1UsersGet(ctx, params)
	if err != nil {
		return handleAPIError(msg, err)
	}
	return marshalResponse(msg, &res)
}

// V1UsersIDGet processor — get /v1/users/{id}

func init() {
	service.MustRegisterBatchProcessor(
		"notion_v1_users_id_get",
		v1UsersIDGetConfig(),
		newV1UsersIDGetProcessor,
	)
}

func v1UsersIDGetConfig() *service.ConfigSpec {
	return service.NewConfigSpec().
		Categories("Services", "Notion").
		Summary("Retrieve a user `GET /v1/users/{id}`").
		Description("Retrieve a user object using the ID specified in the request path.").
		Fields(sharedConfigFields()...).Fields(
		service.NewInterpolatedStringField("id").
			Description(""),
	)
}

type v1UsersIDGetProcessor struct {
	baseProcessor
	id *service.InterpolatedString
}

func newV1UsersIDGetProcessor(conf *service.ParsedConfig, mgr *service.Resources) (service.BatchProcessor, error) {
	base, err := baseProcessorFromParsed(conf, mgr)
	if err != nil {
		return nil, err
	}

	p := &v1UsersIDGetProcessor{baseProcessor: base}
	if p.id, err = conf.FieldInterpolatedString("id"); err != nil {
		return nil, err
	}

	return p, nil
}

func (p *v1UsersIDGetProcessor) ProcessBatch(ctx context.Context, batch service.MessageBatch) ([]service.MessageBatch, error) {
	batch = batch.Copy()

	var wg sync.WaitGroup
	wg.Add(len(batch))
	for i := range batch {
		go func(idx int) {
			defer wg.Done()
			if err := p.processV1UsersIDGet(ctx, idx, batch); err != nil {
				batch[idx].SetError(err)
			}
		}(i)
	}
	wg.Wait()

	return []service.MessageBatch{batch}, nil
}

func (p *v1UsersIDGetProcessor) processV1UsersIDGet(ctx context.Context, idx int, batch service.MessageBatch) error {
	msg := batch[idx]
	params := v1.V1UsersIDGetParams{
		NotionVersion: v1.NewOptString(p.notionVersion),
	}
	{
		v, err := batch.TryInterpolatedString(idx, p.id)
		if err != nil {
			return fmt.Errorf("interpolating id: %w", err)
		}
		params.ID = v
	}
	res, err := p.client.V1UsersIDGet(ctx, params)
	if err != nil {
		return handleAPIError(msg, err)
	}
	return marshalResponse(msg, &res)
}

// V1UsersMeGet processor — get /v1/users/me

func init() {
	service.MustRegisterBatchProcessor(
		"notion_v1_users_me_get",
		v1UsersMeGetConfig(),
		newV1UsersMeGetProcessor,
	)
}

func v1UsersMeGetConfig() *service.ConfigSpec {
	return service.NewConfigSpec().
		Categories("Services", "Notion").
		Summary("Retrieve your token’s bot user `GET /v1/users/me`").
		Fields(sharedConfigFields()...).Fields()
}

type v1UsersMeGetProcessor struct {
	baseProcessor
}

func newV1UsersMeGetProcessor(conf *service.ParsedConfig, mgr *service.Resources) (service.BatchProcessor, error) {
	base, err := baseProcessorFromParsed(conf, mgr)
	if err != nil {
		return nil, err
	}

	p := &v1UsersMeGetProcessor{baseProcessor: base}

	return p, nil
}

func (p *v1UsersMeGetProcessor) ProcessBatch(ctx context.Context, batch service.MessageBatch) ([]service.MessageBatch, error) {
	batch = batch.Copy()

	var wg sync.WaitGroup
	wg.Add(len(batch))
	for i := range batch {
		go func(idx int) {
			defer wg.Done()
			if err := p.processV1UsersMeGet(ctx, idx, batch); err != nil {
				batch[idx].SetError(err)
			}
		}(i)
	}
	wg.Wait()

	return []service.MessageBatch{batch}, nil
}

func (p *v1UsersMeGetProcessor) processV1UsersMeGet(ctx context.Context, idx int, batch service.MessageBatch) error {
	msg := batch[idx]
	params := v1.V1UsersMeGetParams{
		NotionVersion: v1.NewOptString(p.notionVersion),
	}
	res, err := p.client.V1UsersMeGet(ctx, params)
	if err != nil {
		return handleAPIError(msg, err)
	}
	return marshalResponse(msg, &res)
}
