version: "3"

tasks:
  openapi:
    desc: Download OpenAPI spec from Notion developer docs
    cmds:
      - curl -sSfL https://developers.notion.com/openapi.json -o openapi.json
    generates:
      - openapi.json

  procgen:
    desc: Generate Go client and processors from OpenAPI spec
    deps: [openapi]
    cmds:
      - >-
        go run ../procgen
        --service notion
        --template ../processors.go.tmpl
        --package .
        ../ogen.yaml openapi.json
