{
 "title": "Benthos Dash",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "In v Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(benthos_input_read_success[30s])",
     "legendFormat": "Input"
    },
    {
     "expr": "rate(benthos_output_success[30s])",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Buffer Use",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(benthos_buffer_backlog[10s])",
     "legendFormat": "Backlog"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"benthos:4195\"}[30s]) * 100",
     "legendFormat": "Benthos"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"benthos:4195\"}",
     "legendFormat": "Resident"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=\"benthos:4195\"}",
     "legendFormat": "Virtual"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Input Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "benthos_input_latency", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Buffer Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "benthos_buffer_latency", "legendFormat": "{{quantile}}" }
   ]
  }
 ]
}