input:
  generate:
    # Generate 100MB/s stream of data
    interval: 10ms
    batch_size: 1_000
    mapping: |
      root = "REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_R"

output:
  processors:
    - benchmark:
        count_bytes: true

  kafka_franz:
    seed_brokers: ["src:9092"]
    topic: "test-topic-0"
    partitioner: round_robin
    compression: none
    max_in_flight: 100
