input:
  generate:
    # Generate total 30GB of uncompressed data as fast as possible
    interval: ""
    count: 30_000_000
    batch_size: 1_000
    mapping: |
      root = "REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_REDPANDA_R"

output:
  processors:
    - benchmark:
        count_bytes: true

  kafka_franz:
    seed_brokers: ["src:9092"]
    topic: "test-topic-0"
    partitioner: round_robin
    compression: none
    max_in_flight: 100
