input:
  http_server:
    address: 0.0.0.0:4196
    path: /poke
    allowed_verbs: [ POST, HEAD ]
    cors:
      enabled: true
      allowed_origins:
        - '*'
  processors:
    - metric:
        type: counter
        name: site_visit
        labels:
          host: ${! meta("h") }
          path: ${! meta("p") }
          referrer: ${! meta("r") }
    - bloblang: 'root = deleted()'

metrics:
  mapping: |
    # Only emit our custom metric, and no internal Redpanda Connect metrics.
    root = if ![
      "site_visit",
    ].contains($path) { deleted() } else { $path }
  prometheus: {}
