services:
  benchmark-worker-1:
    image: datastax/openmessaging-benchmark:0.0.2-SNAPSHOT
    depends_on:
      src:
        condition: service_healthy
    command:
      - bin/benchmark-worker
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G
        reservations:
          cpus: 1
          memory: 1G
    restart: always

  benchmark-worker-2:
    image: datastax/openmessaging-benchmark:0.0.2-SNAPSHOT
    depends_on:
      src:
        condition: service_healthy
    command:
      - bin/benchmark-worker
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G
        reservations:
          cpus: 1
          memory: 1G
    restart: always

  benchmark:
    image: datastax/openmessaging-benchmark:0.0.2-SNAPSHOT
    container_name: bench-controller
    depends_on:
      - benchmark-worker-1
      - benchmark-worker-2
    volumes:
      - ./openmessaging/driver.yaml:/opt/benchmark/driver.yaml:ro
      - ./openmessaging/workload.yaml:/opt/benchmark/workload.yaml:ro
    command:
      - bin/benchmark
      - --drivers
      - /opt/benchmark/driver.yaml
      - --workers
      - http://benchmark-worker-1:8080,http://benchmark-worker-2:8080
      - /opt/benchmark/workload.yaml
    deploy:
      resources:
        limits:
          cpus: 0.5
