// Copyright 2026 Redpanda Data, Inc.
//
// Licensed as a Redpanda Enterprise file under the Redpanda Community
// License (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
// https://github.com/redpanda-data/connect/blob/main/licenses/rcl.md

package sqlredo

import (
	"encoding/hex"
	"errors"
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// LobLocatorInfo contains the parsed information from a SELECT_LOB_LOCATOR redo entry.
// The LOB column type (CLOB/BLOB/NCLOB) is not parsed from the SQL here; callers
// should resolve it from the database schema (ALL_TAB_COLUMNS).
type LobLocatorInfo struct {
	Schema   string
	Table    string
	Column   string
	PKValues map[string]any
}

var (
	reLobColumn  = regexp.MustCompile(`(?i)select\s+"([^"]+)"\s+into`)
	reLobTable   = regexp.MustCompile(`(?i)from\s+"([^"]+)"\."([^"]+)"`)
	reLobWherePK = regexp.MustCompile(`"([^"]+)"\s*=\s*'((?:[^']|'')*)'`)
)

// ParseSelectLobLocator parses the PL/SQL DECLARE block generated by Oracle
// LogMiner for SELECT_LOB_LOCATOR (operation 9) entries. It returns the schema,
// table, column name, and the WHERE clause PK values that identify which row
// owns this LOB. The LOB type (CLOB/BLOB/NCLOB) is not parsed here — callers
// should look it up from the database schema instead.
func ParseSelectLobLocator(sql string) (*LobLocatorInfo, error) {
	colMatch := reLobColumn.FindStringSubmatch(sql)
	if colMatch == nil {
		return nil, errors.New("could not find column name in SELECT_LOB_LOCATOR SQL")
	}
	column := colMatch[1]

	tableMatch := reLobTable.FindStringSubmatch(sql)
	if tableMatch == nil {
		return nil, errors.New("could not find schema.table in SELECT_LOB_LOCATOR SQL")
	}
	schema := tableMatch[1]
	table := tableMatch[2]

	// Extract WHERE clause PK pairs, stopping before ROWID.
	pkValues := make(map[string]any)
	whereIdx := strings.Index(strings.ToLower(sql), " where ")
	if whereIdx >= 0 {
		whereClause := sql[whereIdx:]
		if rowidIdx := strings.Index(strings.ToLower(whereClause), "rowid"); rowidIdx >= 0 {
			whereClause = whereClause[:rowidIdx]
		}
		for _, m := range reLobWherePK.FindAllStringSubmatch(whereClause, -1) {
			pkValues[m[1]] = strings.ReplaceAll(m[2], "''", "'")
		}
	}

	return &LobLocatorInfo{
		Schema:   schema,
		Table:    table,
		Column:   column,
		PKValues: pkValues,
	}, nil
}

// LobWriteInfo contains the parsed information from a LOB_WRITE redo entry.
type LobWriteInfo struct {
	Data   []byte
	Offset int64
	Length int64
}

var reLobTrimLength = regexp.MustCompile(`(?i)dbms_lob\.trim\s*\([^,]+,\s*(\d+)\s*\)`)

// ParseLobTrim extracts the new length N from a dbms_lob.trim(locator, N) call
// emitted by Oracle LogMiner for LOB_TRIM (op 11) entries.
func ParseLobTrim(sql string) (int64, error) {
	m := reLobTrimLength.FindStringSubmatch(sql)
	if m == nil {
		return 0, errors.New("could not find dbms_lob.trim() call in LOB_TRIM SQL")
	}
	n, err := strconv.ParseInt(m[1], 10, 64)
	if err != nil {
		return 0, fmt.Errorf("parsing LOB_TRIM length: %w", err)
	}
	return n, nil
}

// ParseLobWrite parses the dbms_lob.write() call generated by Oracle LogMiner
// for LOB_WRITE (operation 10) entries. For CLOB and NCLOB (isBinary=false) the
// data is normally extracted as a plain string literal, but Oracle may also emit
// HEXTORAW() for CLOB/NCLOB in some cases (e.g. zero-padded or null-filled segments);
// for BLOB (isBinary=true) it is always hex-decoded from HEXTORAW().
//
// Expected format (PL/SQL variable with separate buffer assignment):
//
//	buf_c := 'Hello';
//	dbms_lob.write(loc_c, 5, 1, buf_c);
func ParseLobWrite(sql string, isBinary bool) (*LobWriteInfo, error) {
	length, offset, err := findLobWriteParams(sql)
	if err != nil {
		return nil, err
	}

	expr, found := findLobAssignment(sql)
	if !found {
		return nil, errors.New("could not find LOB data in LOB_WRITE SQL")
	}

	var data []byte
	if isBinary {
		hexData, found := findHextoraw(expr)
		if !found {
			return nil, errors.New("could not find HEXTORAW() in LOB_WRITE BLOB data expression")
		}
		if data, err = hex.DecodeString(hexData); err != nil {
			return nil, fmt.Errorf("hex-decoding BLOB data: %w", err)
		}
	} else if expr[0] == '\'' {
		data = []byte(strings.ReplaceAll(expr[1:len(expr)-1], "''", "'"))
	} else {
		// Oracle sometimes emits HEXTORAW() for CLOB/NCLOB data (e.g. zero-padded segments).
		hexData, found := findHextoraw(expr)
		if !found {
			return nil, errors.New("could not find string literal in LOB_WRITE CLOB data expression")
		}
		if data, err = hex.DecodeString(hexData); err != nil {
			return nil, fmt.Errorf("hex-decoding CLOB data: %w", err)
		}
	}
	return &LobWriteInfo{Data: data, Offset: offset, Length: length}, nil
}

const (
	hextoraw = "hextoraw"

	// Latin small letter long s folds to 's' under case-insensitive matching.
	longS = "\u017f"
)

// The scanners below are hand-written equivalents of these regexes, which
// were too slow on multi-KB hex payloads:
//
//	(?i)dbms_lob\.write\s*\([^,]+,\s*(\d+)\s*,\s*(\d+)\s*,
//	(?i):=\s*(HEXTORAW\('[0-9A-Fa-f]*'\)|'(?:[^']|'')*')
//	(?i)HEXTORAW\('([0-9A-Fa-f]*)'\)

func isRegexSpace(c byte) bool {
	return c == ' ' || c == '\t' || c == '\n' || c == '\f' || c == '\r'
}

func isDigit(c byte) bool { return c >= '0' && c <= '9' }

func isHexDigit(c byte) bool {
	return isDigit(c) || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')
}

func skipSpace(s string, i int) int {
	for i < len(s) && isRegexSpace(s[i]) {
		i++
	}
	return i
}

func skipDigits(s string, i int) int {
	for i < len(s) && isDigit(s[i]) {
		i++
	}
	return i
}

// hasPrefixFoldAt reports whether s[i:] starts with the lower case ASCII
// string lower, ignoring case.
func hasPrefixFoldAt(s string, i int, lower string) bool {
	if len(s)-i < len(lower) {
		return false
	}
	for j := 0; j < len(lower); j++ {
		if s[i+j]|0x20 != lower[j] {
			return false
		}
	}
	return true
}

// dbmsLobEndsAt reports whether s[:end] ends with "dbms_lob" and returns true
// if so. The 's' may also be spelled with its Unicode case folding.
func dbmsLobEndsAt(s string, end int) bool {
	const suffix = "lob"
	if end < len(suffix) || !hasPrefixFoldAt(s, end-len(suffix), suffix) {
		return false
	}
	i := end - len(suffix)
	if i < 1 || s[i-1] != '_' {
		return false
	}
	i--
	switch {
	case i >= 1 && s[i-1]|0x20 == 's':
		i--
	case strings.HasSuffix(s[:i], longS):
		i -= len(longS)
	default:
		return false
	}
	return i >= 3 && hasPrefixFoldAt(s, i-3, "dbm")
}

// findLobWriteParams returns the length and offset arguments of the first
// well-formed dbms_lob.write() call in sql.
func findLobWriteParams(sql string) (length, offset int64, err error) {
	for from := 0; from < len(sql); {
		dot := strings.IndexByte(sql[from:], '.')
		if dot < 0 {
			break
		}
		dot += from
		from = dot + 1
		if !dbmsLobEndsAt(sql, dot) || !hasPrefixFoldAt(sql, dot+1, "write") {
			continue
		}

		i := skipSpace(sql, dot+1+len("write"))
		if i >= len(sql) || sql[i] != '(' {
			continue
		}
		i++
		// The locator argument is one or more non-comma characters.
		comma := strings.IndexByte(sql[i:], ',')
		if comma < 1 {
			continue
		}
		i = skipSpace(sql, i+comma+1)

		lenStart := i
		if i = skipDigits(sql, i); i == lenStart {
			continue
		}
		lenStr := sql[lenStart:i]
		if i = skipSpace(sql, i); i >= len(sql) || sql[i] != ',' {
			continue
		}
		i = skipSpace(sql, i+1)

		offStart := i
		if i = skipDigits(sql, i); i == offStart {
			continue
		}
		offStr := sql[offStart:i]
		if i = skipSpace(sql, i); i >= len(sql) || sql[i] != ',' {
			continue
		}

		if length, err = strconv.ParseInt(lenStr, 10, 64); err != nil {
			return 0, 0, fmt.Errorf("parsing LOB write length: %w", err)
		}
		if offset, err = strconv.ParseInt(offStr, 10, 64); err != nil {
			return 0, 0, fmt.Errorf("parsing LOB write offset: %w", err)
		}
		return length, offset, nil
	}
	return 0, 0, errors.New("could not parse dbms_lob.write() call in LOB_WRITE SQL")
}

// findLobAssignment returns the value of the first ":=" that is followed by a
// HEXTORAW('...') call or a quoted string literal, including the quotes.
func findLobAssignment(sql string) (string, bool) {
	for from := 0; from < len(sql); {
		idx := strings.Index(sql[from:], ":=")
		if idx < 0 {
			break
		}
		from += idx + 1
		start := skipSpace(sql, from+1)
		if start >= len(sql) {
			break
		}
		switch {
		case sql[start] == '\'':
			if end, ok := scanQuoted(sql[start:]); ok {
				return sql[start : start+end], true
			}
		case sql[start]|0x20 == 'h':
			if _, end, ok := matchHextoraw(sql, start); ok {
				return sql[start:end], true
			}
		}
	}
	return "", false
}

// scanQuoted returns the length of the string literal at the start of s, where
// a doubled quote is an escaped quote. As in a backtracking match, an escape
// pair is preferred but gives way to a closing quote when no later quote
// terminates the literal.
func scanQuoted(s string) (int, bool) {
	var (
		i        = 1
		lastPair = -1
	)
	for {
		q := strings.IndexByte(s[i:], '\'')
		if q < 0 {
			if lastPair >= 0 {
				return lastPair + 1, true
			}
			return 0, false
		}
		q += i
		if q+1 < len(s) && s[q+1] == '\'' {
			lastPair = q
			i = q + 2
			continue
		}
		return q + 1, true
	}
}

// matchHextoraw matches HEXTORAW('<hex>') at s[i:], returning the hex digits
// and the index just past the closing parenthesis.
func matchHextoraw(s string, i int) (hexData string, end int, ok bool) {
	const open = len(hextoraw) + 2 // HEXTORAW('
	if !hasPrefixFoldAt(s, i, hextoraw) || len(s)-i < open || s[i+len(hextoraw)] != '(' || s[i+len(hextoraw)+1] != '\'' {
		return "", 0, false
	}
	start := i + open
	j := start
	for j < len(s) && isHexDigit(s[j]) {
		j++
	}
	if j+1 >= len(s) || s[j] != '\'' || s[j+1] != ')' {
		return "", 0, false
	}
	return s[start:j], j + 2, true
}

// findHextoraw returns the hex digits of the first HEXTORAW('<hex>') in s.
func findHextoraw(s string) (string, bool) {
	for i := 0; i < len(s); i++ {
		if s[i]|0x20 != 'h' {
			continue
		}
		if hexData, _, ok := matchHextoraw(s, i); ok {
			return hexData, true
		}
	}
	return "", false
}
