// Copyright 2026 Redpanda Data, Inc.
//
// Licensed as a Redpanda Enterprise file under the Redpanda Community
// License (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
// https://github.com/redpanda-data/connect/blob/main/licenses/rcl.md

package sqlredo

import (
	"encoding/hex"
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// LobLocatorInfo contains the parsed information from a SELECT_LOB_LOCATOR redo entry.
// The LOB column type (CLOB/BLOB/NCLOB) is not parsed from the SQL here; callers
// should resolve it from the database schema (ALL_TAB_COLUMNS).
type LobLocatorInfo struct {
	Schema   string
	Table    string
	Column   string
	PKValues map[string]any
}

var (
	reLobColumn  = regexp.MustCompile(`(?i)select\s+"([^"]+)"\s+into`)
	reLobTable   = regexp.MustCompile(`(?i)from\s+"([^"]+)"\."([^"]+)"`)
	reLobWherePK = regexp.MustCompile(`"([^"]+)"\s*=\s*'((?:[^']|'')*)'`)
)

// ParseSelectLobLocator parses the PL/SQL DECLARE block generated by Oracle
// LogMiner for SELECT_LOB_LOCATOR (operation 9) entries. It returns the schema,
// table, column name, and the WHERE clause PK values that identify which row
// owns this LOB. The LOB type (CLOB/BLOB/NCLOB) is not parsed here — callers
// should look it up from the database schema instead.
func ParseSelectLobLocator(sql string) (*LobLocatorInfo, error) {
	colMatch := reLobColumn.FindStringSubmatch(sql)
	if colMatch == nil {
		return nil, fmt.Errorf("could not find column name in SELECT_LOB_LOCATOR SQL")
	}
	column := colMatch[1]

	tableMatch := reLobTable.FindStringSubmatch(sql)
	if tableMatch == nil {
		return nil, fmt.Errorf("could not find schema.table in SELECT_LOB_LOCATOR SQL")
	}
	schema := tableMatch[1]
	table := tableMatch[2]

	// Extract WHERE clause PK pairs, stopping before ROWID.
	pkValues := make(map[string]any)
	whereIdx := strings.Index(strings.ToLower(sql), " where ")
	if whereIdx >= 0 {
		whereClause := sql[whereIdx:]
		if rowidIdx := strings.Index(strings.ToLower(whereClause), "rowid"); rowidIdx >= 0 {
			whereClause = whereClause[:rowidIdx]
		}
		for _, m := range reLobWherePK.FindAllStringSubmatch(whereClause, -1) {
			pkValues[m[1]] = strings.ReplaceAll(m[2], "''", "'")
		}
	}

	return &LobLocatorInfo{
		Schema:   schema,
		Table:    table,
		Column:   column,
		PKValues: pkValues,
	}, nil
}

// LobWriteInfo contains the parsed information from a LOB_WRITE redo entry.
type LobWriteInfo struct {
	Data   []byte
	Offset int64
	Length int64
}

var (
	// Old format: dbms_lob.write(:bindvar, length, offset, literal_or_hextoraw)
	// The first argument is a bind variable prefixed with ':'.
	reLobWriteOld = regexp.MustCompile(`(?i)dbms_lob\.write\s*\(\s*:[^,]+,\s*(\d+)\s*,\s*(\d+)\s*,\s*(.*?)\s*\)\s*;?\s*$`)

	// New format: dbms_lob.write(locvar, length, offset, bufvar)
	// Both locvar and bufvar are plain PL/SQL identifiers (no ':' prefix).
	// Data is assigned to bufvar on a preceding line: buf_c/buf_nc := 'text'; or buf_b := HEXTORAW('hex');
	reLobWriteNew = regexp.MustCompile(`(?i)dbms_lob\.write\s*\(\s*\w+\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\w+)\s*\)`)

	reLobHextoraw   = regexp.MustCompile(`(?i)HEXTORAW\('([0-9A-Fa-f]*)'\)`)
	reLobStrLiteral = regexp.MustCompile(`^'((?:[^']|'')*)'$`)

	// New-format buffer variable assignments. Capture the variable name (group 1)
	// and the value (group 2) so these can be pre-compiled at package level rather
	// than constructed per call.
	reLobNewBufHex = regexp.MustCompile(`(?i)\b(\w+)\s*:=\s*HEXTORAW\('([0-9A-Fa-f]*)'\)`)
	reLobNewBufStr = regexp.MustCompile(`(?i)\b(\w+)\s*:=\s*'((?:[^']|'')*)'`)
)

// ParseLobWrite parses the dbms_lob.write() call generated by Oracle LogMiner
// for LOB_WRITE (operation 10) entries. For CLOB and NCLOB (isBinary=false) the
// data is extracted as a plain string; for BLOB (isBinary=true) it is hex-decoded.
//
// Two SQL formats are supported:
//
//   Old format (bind variable):
//     dbms_lob.write(:1, 5, 1, 'Hello');
//     dbms_lob.write(:1, 5, 1, HEXTORAW('48656C6C6F'));
//
//   New format (PL/SQL variable with separate buffer assignment):
//     buf_c := 'Hello';
//     dbms_lob.write(loc_c, 5, 1, buf_c);
func ParseLobWrite(sql string, isBinary bool) (*LobWriteInfo, error) {
	// Try old format first: first arg is a bind variable (:1, :loc, etc.).
	if m := reLobWriteOld.FindStringSubmatch(strings.TrimSpace(sql)); m != nil {
		return parseLobWriteOldFmt(m, isBinary)
	}

	// Try new format: first arg is a plain PL/SQL identifier (loc_c, loc_b, etc.).
	if m := reLobWriteNew.FindStringSubmatch(sql); m != nil {
		return parseLobWriteNewFmt(sql, m, isBinary)
	}

	return nil, fmt.Errorf("could not parse dbms_lob.write() call in LOB_WRITE SQL")
}

func parseLobWriteOldFmt(m []string, isBinary bool) (*LobWriteInfo, error) {
	length, err := strconv.ParseInt(m[1], 10, 64)
	if err != nil {
		return nil, fmt.Errorf("parsing LOB write length: %w", err)
	}
	offset, err := strconv.ParseInt(m[2], 10, 64)
	if err != nil {
		return nil, fmt.Errorf("parsing LOB write offset: %w", err)
	}
	dataExpr := strings.TrimSpace(m[3])

	var data []byte
	if isBinary {
		hexMatch := reLobHextoraw.FindStringSubmatch(dataExpr)
		if hexMatch == nil {
			return nil, fmt.Errorf("could not find HEXTORAW() in LOB_WRITE BLOB data expression")
		}
		data, err = hex.DecodeString(hexMatch[1])
		if err != nil {
			return nil, fmt.Errorf("hex-decoding BLOB data: %w", err)
		}
	} else {
		strMatch := reLobStrLiteral.FindStringSubmatch(dataExpr)
		if strMatch == nil {
			return nil, fmt.Errorf("could not find string literal in LOB_WRITE CLOB data expression")
		}
		data = []byte(strings.ReplaceAll(strMatch[1], "''", "'"))
	}
	return &LobWriteInfo{Data: data, Offset: offset, Length: length}, nil
}

func parseLobWriteNewFmt(sql string, m []string, isBinary bool) (*LobWriteInfo, error) {
	length, err := strconv.ParseInt(m[1], 10, 64)
	if err != nil {
		return nil, fmt.Errorf("parsing LOB write length: %w", err)
	}
	offset, err := strconv.ParseInt(m[2], 10, 64)
	if err != nil {
		return nil, fmt.Errorf("parsing LOB write offset: %w", err)
	}
	bufVar := m[3]

	var data []byte
	if isBinary {
		// buf_b := HEXTORAW('...')
		hexMatch := reLobNewBufHex.FindStringSubmatch(sql)
		if hexMatch == nil || !strings.EqualFold(hexMatch[1], bufVar) {
			return nil, fmt.Errorf("could not find HEXTORAW() assignment for %s in LOB_WRITE SQL", bufVar)
		}
		data, err = hex.DecodeString(hexMatch[2])
		if err != nil {
			return nil, fmt.Errorf("hex-decoding LOB data: %w", err)
		}
	} else {
		// buf_c / buf_nc := 'text...'
		strMatch := reLobNewBufStr.FindStringSubmatch(sql)
		if strMatch == nil || !strings.EqualFold(strMatch[1], bufVar) {
			return nil, fmt.Errorf("could not find string assignment for %s in LOB_WRITE SQL", bufVar)
		}
		data = []byte(strings.ReplaceAll(strMatch[2], "''", "'"))
	}
	return &LobWriteInfo{Data: data, Offset: offset, Length: length}, nil
}
