// Copyright 2026 Redpanda Data, Inc.
//
// Licensed as a Redpanda Enterprise file under the Redpanda Community
// License (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
// https://github.com/redpanda-data/connect/blob/main/licenses/rcl.md

package sqlredo

import (
	"encoding/hex"
	"errors"
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// LobLocatorInfo contains the parsed information from a SELECT_LOB_LOCATOR redo entry.
// The LOB column type (CLOB/BLOB/NCLOB) is not parsed from the SQL here; callers
// should resolve it from the database schema (ALL_TAB_COLUMNS).
type LobLocatorInfo struct {
	Schema   string
	Table    string
	Column   string
	PKValues map[string]any
}

var (
	reLobColumn  = regexp.MustCompile(`(?i)select\s+"([^"]+)"\s+into`)
	reLobTable   = regexp.MustCompile(`(?i)from\s+"([^"]+)"\."([^"]+)"`)
	reLobWherePK = regexp.MustCompile(`"([^"]+)"\s*=\s*'((?:[^']|'')*)'`)
)

// ParseSelectLobLocator parses the PL/SQL DECLARE block generated by Oracle
// LogMiner for SELECT_LOB_LOCATOR (operation 9) entries. It returns the schema,
// table, column name, and the WHERE clause PK values that identify which row
// owns this LOB. The LOB type (CLOB/BLOB/NCLOB) is not parsed here — callers
// should look it up from the database schema instead.
func ParseSelectLobLocator(sql string) (*LobLocatorInfo, error) {
	colMatch := reLobColumn.FindStringSubmatch(sql)
	if colMatch == nil {
		return nil, errors.New("could not find column name in SELECT_LOB_LOCATOR SQL")
	}
	column := colMatch[1]

	tableMatch := reLobTable.FindStringSubmatch(sql)
	if tableMatch == nil {
		return nil, errors.New("could not find schema.table in SELECT_LOB_LOCATOR SQL")
	}
	schema := tableMatch[1]
	table := tableMatch[2]

	// Extract WHERE clause PK pairs, stopping before ROWID.
	pkValues := make(map[string]any)
	whereIdx := strings.Index(strings.ToLower(sql), " where ")
	if whereIdx >= 0 {
		whereClause := sql[whereIdx:]
		if rowidIdx := strings.Index(strings.ToLower(whereClause), "rowid"); rowidIdx >= 0 {
			whereClause = whereClause[:rowidIdx]
		}
		for _, m := range reLobWherePK.FindAllStringSubmatch(whereClause, -1) {
			pkValues[m[1]] = strings.ReplaceAll(m[2], "''", "'")
		}
	}

	return &LobLocatorInfo{
		Schema:   schema,
		Table:    table,
		Column:   column,
		PKValues: pkValues,
	}, nil
}

// LobWriteInfo contains the parsed information from a LOB_WRITE redo entry.
type LobWriteInfo struct {
	Data   []byte
	Offset int64
	Length int64
}

var (
	// Extracts length (1) and offset (2) from dbms_lob.write.
	reLobWriteParams = regexp.MustCompile(`(?i)dbms_lob\.write\s*\([^,]+,\s*(\d+)\s*,\s*(\d+)\s*,`)

	// Data is assigned to a buffer variable before the write call.
	// Captures the value — either a quoted string or HEXTORAW(...).
	reLobAssignment = regexp.MustCompile(`(?i):=\s*(HEXTORAW\('[0-9A-Fa-f]*'\)|'(?:[^']|'')*')`)

	reLobHextoraw   = regexp.MustCompile(`(?i)HEXTORAW\('([0-9A-Fa-f]*)'\)`)
	reLobStrLiteral = regexp.MustCompile(`^'((?:[^']|'')*)'$`)
)

// ParseLobWrite parses the dbms_lob.write() call generated by Oracle LogMiner
// for LOB_WRITE (operation 10) entries. For CLOB and NCLOB (isBinary=false) the
// data is extracted as a plain string; for BLOB (isBinary=true) it is hex-decoded.
//
// Expected format (PL/SQL variable with separate buffer assignment):
//
//	buf_c := 'Hello';
//	dbms_lob.write(loc_c, 5, 1, buf_c);
func ParseLobWrite(sql string, isBinary bool) (*LobWriteInfo, error) {
	var (
		length int64
		offset int64
		data   []byte
		err    error
	)

	paramsMatch := reLobWriteParams.FindStringSubmatch(sql)
	if paramsMatch == nil {
		return nil, errors.New("could not parse dbms_lob.write() call in LOB_WRITE SQL")
	}
	if length, err = strconv.ParseInt(paramsMatch[1], 10, 64); err != nil {
		return nil, fmt.Errorf("parsing LOB write length: %w", err)
	}
	if offset, err = strconv.ParseInt(paramsMatch[2], 10, 64); err != nil {
		return nil, fmt.Errorf("parsing LOB write offset: %w", err)
	}

	var expr string
	if m := reLobAssignment.FindStringSubmatch(sql); m != nil {
		expr = m[1]
	} else {
		return nil, errors.New("could not find LOB data in LOB_WRITE SQL")
	}

	if isBinary {
		matchHex := reLobHextoraw.FindStringSubmatch(expr)
		if matchHex == nil {
			return nil, errors.New("could not find HEXTORAW() in LOB_WRITE BLOB data expression")
		}
		if data, err = hex.DecodeString(matchHex[1]); err != nil {
			return nil, fmt.Errorf("hex-decoding BLOB data: %w", err)
		}
	} else {
		matchStr := reLobStrLiteral.FindStringSubmatch(expr)
		if matchStr == nil {
			return nil, errors.New("could not find string literal in LOB_WRITE CLOB data expression")
		}
		data = []byte(strings.ReplaceAll(matchStr[1], "''", "'"))
	}
	return &LobWriteInfo{Data: data, Offset: offset, Length: length}, nil
}
