{
 "title": "Enrichment Dash",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prefix", "label": "Metrics Prefix", "query": "benthos" }
  ]
 },
 "panels": [
  { "title": "Enrichments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${prefix}_processor_process__dag_processor_process__map_error/${prefix}_processor_process__dag_processor_process__map_count",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "HTTP Response Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({__name__=~\"${prefix}_processor_process__dag_processor_process__map_processor_http_client_http_code_5[0-9]*\"}[30s])",
     "legendFormat": "{{id}} 5XX"
    },
    {
     "expr": "rate({__name__=~\"${prefix}_processor_process__dag_processor_process__map_processor_http_client_http_code_4[0-9]*\"}[30s])",
     "legendFormat": "{{id}} 4XX"
    },
    {
     "expr": "rate({__name__=~\"${prefix}_processor_process__dag_processor_process__map_processor_http_client_http_code_3[0-9]*\"}[30s])",
     "legendFormat": "{{id}} 3XX"
    },
    {
     "expr": "rate({__name__=~\"${prefix}_processor_process__dag_processor_process__map_processor_http_client_http_code_2[0-9]*\"}[30s])",
     "legendFormat": "{{id}} 2XX"
    }
   ]
  },
  {
   "title": "HTTP Latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "${prefix}_processor_process__dag_processor_process__map_processor_http_client_http_latency",
     "legendFormat": "{{id}} {{quantile}}"
    }
   ]
  },
  { "title": "Pipeline Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "In v Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(${prefix}_input_count[30s])",
     "legendFormat": "Input"
    },
    {
     "expr": "rate(${prefix}_output_success[30s])",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Input Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "${prefix}_input_latency", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance=\"benthos:4195\"}[30s]) * 100",
       "legendFormat": "benthos"
      }
     ]
    },
    {
     "title": "Mem Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=\"benthos:4195\"}",
       "legendFormat": "Resident"
      },
      {
       "expr": "process_virtual_memory_bytes{instance=\"benthos:4195\"}",
       "legendFormat": "Virtual"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffer Use",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(${prefix}_buffer_backlog[10s])",
       "legendFormat": "Backlog"
      }
     ]
    },
    {
     "title": "Buffer Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      { "expr": "${prefix}_buffer_latency", "legendFormat": "{{quantile}}" }
     ]
    }
   ]
  }
 ]
}