// Copyright 2026 Redpanda Data, Inc.
//
// Licensed as a Redpanda Enterprise file under the Redpanda Community
// License (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
// https://github.com/redpanda-data/connect/blob/main/licenses/rcl.md

// Package procgen generates Redpanda Connect processors from OpenAPI specs.
package procgen

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
	"unicode"

	"github.com/go-faster/yaml"
	"github.com/ogen-go/ogen"
	"github.com/ogen-go/ogen/gen"
	"github.com/ogen-go/ogen/gen/genfs"
	"github.com/ogen-go/ogen/gen/ir"
	"github.com/ogen-go/ogen/openapi"
	"go.uber.org/zap"
	"golang.org/x/tools/imports"
)

// TemplateData is the top-level data passed to the processor template.
type TemplateData struct {
	Package          string
	APIPackage       string
	Service          string       // "notion"
	DefaultServerURL string       // "https://api.notion.com"
	Security         SecurityInfo // Auth method from spec
	SharedHeaders    []SharedHeader
	Operations       []OpInfo
}

// SecurityInfo describes the authentication method generated by ogen.
type SecurityInfo struct {
	Method string // "BearerAuth"
	Type   string // "BearerAuth"
	Field  string // "Token"
}

// SharedHeader describes a header parameter shared across all operations.
type SharedHeader struct {
	HeaderName   string // "Notion-Version"
	FieldName    string // "notion_version"
	GoParamName  string // "NotionVersion"
	GoType       string // "OptString"
	DefaultValue string // "2022-06-28"
	Description  string
}

// OpInfo describes a single API operation for template rendering.
type OpInfo struct {
	Name            string // "BlocksIDChildrenGet"
	ProcessorName   string // "notion_blocks_id_children_get"
	Summary         string
	Description     string
	HTTPMethod      string
	Path            string
	PathParams      []ParamInfo
	QueryParams     []ParamInfo
	HasRequestBody  bool
	RequestTypeName string // "QueryDataSourceBodyParameters"
	ParamsTypeName  string // "BlocksIDChildrenGetParams"
}

// AllParams returns path and query params combined.
func (o OpInfo) AllParams() []ParamInfo {
	return append(o.PathParams, o.QueryParams...)
}

// ParamInfo describes a single parameter for template rendering.
type ParamInfo struct {
	FieldName   string // "id", "page_size"
	GoFieldName string // "id", "pageSize"
	GoParamName string // "ID", "PageSize"
	GoType      string // "string", "OptInt", "OptString"
	Required    bool
	Description string
}

// IsOptString returns true if the Go type is OptString.
func (p ParamInfo) IsOptString() bool { return p.GoType == "OptString" }

// IsOptInt returns true if the Go type is OptInt.
func (p ParamInfo) IsOptInt() bool { return p.GoType == "OptInt" }

// Run is the main entry point for the processor code generator.
//
// Usage: procgen [flags] <ogen-config> <openapi-spec>
//
// Flags:
//
//	--service       Service name (e.g. Notion) — required
//	--template      Path to Go template file — required
//	--package       Processor output directory (default: impl/<service>)
//	--api-package   API client output directory (default: <package>/api/v1)
func Run(args []string) error {
	set := flag.NewFlagSet("procgen", flag.ContinueOnError)

	service := set.String("service", "", "Service name (e.g. Notion)")
	tmplPath := set.String("template", "", "Path to Go template file")
	pkg := set.String("package", "", "Processor output directory (default: impl/<service>)")
	apiPackage := set.String("api-package", "", "API client output directory (default: <package>/api/v1)")

	if err := set.Parse(args); err != nil {
		return err
	}

	if *service == "" {
		return fmt.Errorf("--service is required")
	}
	if *tmplPath == "" {
		return fmt.Errorf("--template is required")
	}
	if set.NArg() != 2 {
		return fmt.Errorf("usage: procgen [flags] <ogen-config> <openapi-spec>")
	}

	cfgPath := set.Arg(0)
	specPath := set.Arg(1)

	prefix := *service // already lowercase, e.g. "notion"
	pkgDir := *pkg
	if pkgDir == "" {
		pkgDir = filepath.Join("impl", prefix)
	}
	apiDir := *apiPackage
	if apiDir == "" {
		apiDir = filepath.Join(pkgDir, "api", "v1")
	}
	apiPkgName := filepath.Base(apiDir)
	outputFilename := prefix + "_processors.go"

	// Determine processor package name.
	procPkgName, err := resolvePackageName(pkgDir)
	if err != nil {
		return fmt.Errorf("resolving package name for %s: %w", pkgDir, err)
	}

	// Resolve module path and root directory.
	modulePath, moduleRoot, err := goModuleInfo()
	if err != nil {
		return fmt.Errorf("detecting go module: %w", err)
	}

	// Compute import paths from module root.
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getting working directory: %w", err)
	}

	relFromRoot, err := filepath.Rel(moduleRoot, cwd)
	if err != nil {
		return fmt.Errorf("computing relative path: %w", err)
	}

	apiImportPath := modulePath + "/" + filepath.ToSlash(filepath.Join(relFromRoot, apiDir))

	// Read template file.
	tmplData, err := os.ReadFile(*tmplPath)
	if err != nil {
		return fmt.Errorf("reading template: %w", err)
	}

	// Load ogen config.
	opts, err := loadOgenConfig(cfgPath)
	if err != nil {
		return fmt.Errorf("loading ogen config: %w", err)
	}

	// Read and parse the spec.
	specData, err := opts.SetLocation(specPath, gen.RemoteOptions{})
	if err != nil {
		return fmt.Errorf("resolving spec: %w", err)
	}

	spec, err := ogen.Parse(specData)
	if err != nil {
		return fmt.Errorf("parsing spec: %w", err)
	}

	// Extract default server URL from spec.
	defaultURL := ""
	if len(spec.Servers) > 0 {
		defaultURL = spec.Servers[0].URL
	}

	// Build IR.
	g, err := gen.NewGenerator(spec, opts)
	if err != nil {
		return fmt.Errorf("building IR: %w", err)
	}

	// Generate ogen API client.
	if err := os.RemoveAll(apiDir); err != nil {
		return fmt.Errorf("removing API dir: %w", err)
	}
	if err := os.MkdirAll(apiDir, 0o750); err != nil {
		return fmt.Errorf("creating API dir: %w", err)
	}

	fs := genfs.FormattedSource{Root: apiDir}
	if err := g.WriteSource(fs, apiPkgName); err != nil {
		return fmt.Errorf("writing ogen source: %w", err)
	}

	// Ensure processor output directory exists.
	if err := os.MkdirAll(pkgDir, 0o750); err != nil {
		return fmt.Errorf("creating package dir: %w", err)
	}

	// Extract security info and build shared header set from operations.
	operations := g.Operations()
	secInfo := extractSecurityInfo(operations)

	// Detect shared header parameters (headers present on all operations).
	sharedHeaders := detectSharedHeaders(operations)
	sharedHeaderNames := make(map[string]bool, len(sharedHeaders))
	for _, sh := range sharedHeaders {
		sharedHeaderNames[strings.ToLower(sh.HeaderName)] = true
	}

	// Build template data and generate processor file.
	td := TemplateData{
		Package:          procPkgName,
		APIPackage:       apiImportPath,
		Service:          prefix,
		DefaultServerURL: defaultURL,
		Security:         secInfo,
		SharedHeaders:    sharedHeaders,
		Operations:       buildOps(operations, prefix, sharedHeaderNames),
	}

	if err := generateProcessorFile(td, string(tmplData), pkgDir, outputFilename); err != nil {
		return fmt.Errorf("generating processors: %w", err)
	}

	return nil
}

// resolvePackageName determines the Go package name for a directory.
// For existing directories with Go files, it reads the package name from them.
// For "." it resolves to the current directory's package name.
// For new directories, it uses the last path element.
func resolvePackageName(dir string) (string, error) {
	absDir, err := filepath.Abs(dir)
	if err != nil {
		return "", err
	}

	// Check if the directory has any Go files we can read the package from.
	entries, err := os.ReadDir(absDir)
	if err == nil {
		for _, e := range entries {
			if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
				continue
			}
			// Skip test files and generated files.
			if strings.HasSuffix(e.Name(), "_test.go") {
				continue
			}
			content, err := os.ReadFile(filepath.Join(absDir, e.Name()))
			if err != nil {
				continue
			}
			for _, line := range strings.Split(string(content), "\n") {
				line = strings.TrimSpace(line)
				if strings.HasPrefix(line, "package ") {
					pkg := strings.TrimSpace(strings.TrimPrefix(line, "package"))
					// Remove trailing comments.
					if idx := strings.Index(pkg, "//"); idx >= 0 {
						pkg = strings.TrimSpace(pkg[:idx])
					}
					if pkg != "" {
						return pkg, nil
					}
				}
			}
		}
	}

	// Fall back to directory name.
	return filepath.Base(absDir), nil
}

// goModuleInfo returns the module path and the root directory containing go.mod.
func goModuleInfo() (modulePath string, moduleRoot string, err error) {
	modPath, err := exec.Command("go", "env", "GOMOD").Output()
	if err != nil {
		return "", "", fmt.Errorf("running go env GOMOD: %w", err)
	}
	gomod := strings.TrimSpace(string(modPath))
	if gomod == "" || gomod == os.DevNull {
		return "", "", fmt.Errorf("not inside a Go module")
	}
	moduleRoot = filepath.Dir(gomod)

	modContent, err := os.ReadFile(gomod)
	if err != nil {
		return "", "", err
	}
	for _, line := range strings.Split(string(modContent), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "module ") {
			modulePath = strings.TrimSpace(strings.TrimPrefix(line, "module"))
			return modulePath, moduleRoot, nil
		}
	}
	return "", "", fmt.Errorf("module directive not found in %s", gomod)
}

func loadOgenConfig(cfgPath string) (gen.Options, error) {
	var opts gen.Options
	opts.Logger = zap.NewNop()

	if cfgPath == "" {
		return opts, nil
	}

	data, err := os.ReadFile(cfgPath)
	if err != nil {
		return opts, err
	}

	d := yaml.NewDecoder(bytes.NewReader(data))
	d.KnownFields(true)
	if err := d.Decode(&opts); err != nil {
		return opts, err
	}
	opts.Logger = zap.NewNop()

	return opts, nil
}

// detectSharedHeaders finds header parameters that appear on all operations
// and returns them as SharedHeader values. Only headers with a default value
// in the spec are included.
func detectSharedHeaders(ops []*ir.Operation) []SharedHeader {
	if len(ops) == 0 {
		return nil
	}

	// Count how many operations each header appears in.
	type headerInfo struct {
		param *ir.Parameter
		count int
	}
	headers := make(map[string]*headerInfo)

	for _, op := range ops {
		for _, p := range op.Params {
			if p.Spec == nil || p.Spec.In != openapi.LocationHeader {
				continue
			}
			name := strings.ToLower(p.Spec.Name)
			// Skip standard auth/content-type headers.
			if name == "authorization" || name == "content-type" {
				continue
			}
			if h, ok := headers[name]; ok {
				h.count++
			} else {
				headers[name] = &headerInfo{param: p, count: 1}
			}
		}
	}

	// Only include headers present on every operation.
	var out []SharedHeader
	for _, h := range headers {
		if h.count != len(ops) {
			continue
		}
		p := h.param

		defaultVal := ""
		if p.Spec.Schema != nil && p.Spec.Schema.DefaultSet {
			defaultVal = fmt.Sprint(p.Spec.Schema.Default)
		}

		out = append(out, SharedHeader{
			HeaderName:   p.Spec.Name,
			FieldName:    pascalToSnake(p.Name),
			GoParamName:  p.Name,
			GoType:       p.Type.Go(),
			DefaultValue: defaultVal,
			Description:  p.Spec.Description,
		})
	}
	return out
}

func extractSecurityInfo(ops []*ir.Operation) SecurityInfo {
	for _, op := range ops {
		if op.Security.Securities == nil {
			continue
		}
		for _, sec := range op.Security.Securities {
			return SecurityInfo{
				Method: sec.Type.Name,
				Type:   sec.Type.Name,
				Field:  securityField(sec),
			}
		}
	}
	return SecurityInfo{}
}

func securityField(sec *ir.Security) string {
	if sec.Format.IsBearerSecurity() {
		return "Token"
	}
	if sec.Format.IsBasicHTTPSecurity() {
		return "Username"
	}
	if sec.Format.IsAPIKeySecurity() {
		return "APIKey"
	}
	return "Token"
}

func buildOps(ops []*ir.Operation, prefix string, sharedHeaderNames map[string]bool) []OpInfo {
	out := make([]OpInfo, 0, len(ops))
	for _, op := range ops {
		info := OpInfo{
			Name:           op.Name,
			ProcessorName:  prefix + "_" + pascalToSnake(op.Name),
			Summary:        op.Summary,
			Description:    op.Description,
			HTTPMethod:     op.Spec.HTTPMethod,
			Path:           op.Spec.Path.String(),
			ParamsTypeName: op.Name + "Params",
		}

		for _, p := range op.PathParams() {
			if isSharedParam(p, sharedHeaderNames) {
				continue
			}
			info.PathParams = append(info.PathParams, buildParamInfo(p))
		}

		for _, p := range op.QueryParams() {
			if isSharedParam(p, sharedHeaderNames) {
				continue
			}
			info.QueryParams = append(info.QueryParams, buildParamInfo(p))
		}

		if op.Request != nil && op.Request.Type != nil {
			info.HasRequestBody = true
			info.RequestTypeName = op.Request.Type.Name
		}

		out = append(out, info)
	}
	return out
}

func buildParamInfo(p *ir.Parameter) ParamInfo {
	return ParamInfo{
		FieldName:   p.Spec.Name,
		GoFieldName: toLowerCamel(p.Name),
		GoParamName: p.Name,
		GoType:      p.Type.Go(),
		Required:    p.Spec.Required,
		Description: p.Spec.Description,
	}
}

func isSharedParam(p *ir.Parameter, sharedHeaderNames map[string]bool) bool {
	if p.Spec == nil {
		return false
	}
	if p.Spec.In == openapi.LocationHeader {
		name := strings.ToLower(p.Spec.Name)
		return sharedHeaderNames[name] || name == "authorization" || name == "content-type"
	}
	return false
}

func generateProcessorFile(data TemplateData, tmplContent, targetDir, outputFilename string) error {
	tmpl, err := template.New("processors").Funcs(template.FuncMap{
		"lowerFirst": toLowerCamel,
		"snakeCase":  pascalToSnake,
		"title":      strings.ToTitle,
	}).Parse(tmplContent)
	if err != nil {
		return fmt.Errorf("parsing template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("executing template: %w", err)
	}

	formatted, err := imports.Process(outputFilename, buf.Bytes(), nil)
	if err != nil {
		debugPath := filepath.Join(targetDir, outputFilename+".dump")
		_ = os.WriteFile(debugPath, buf.Bytes(), 0o644)
		return fmt.Errorf("formatting output (raw dumped to %s): %w", debugPath, err)
	}

	outPath := filepath.Join(targetDir, outputFilename)
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		return fmt.Errorf("writing output: %w", err)
	}

	return nil
}

// pascalToSnake converts "BlocksIDChildrenGet" to "blocks_id_children_get".
func pascalToSnake(s string) string {
	var result strings.Builder
	for i, r := range s {
		if unicode.IsUpper(r) {
			if i > 0 {
				prev := rune(s[i-1])
				if unicode.IsLower(prev) {
					result.WriteByte('_')
				} else if unicode.IsUpper(prev) && i+1 < len(s) && unicode.IsLower(rune(s[i+1])) {
					result.WriteByte('_')
				}
			}
			result.WriteRune(unicode.ToLower(r))
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}

// toLowerCamel converts "ID" to "id", "PageSize" to "pageSize", "BlockID" to "blockID".
func toLowerCamel(s string) string {
	if s == "" {
		return s
	}
	i := 0
	for i < len(s) && unicode.IsUpper(rune(s[i])) {
		i++
	}
	if i == 0 {
		return s
	}
	if i == len(s) {
		return strings.ToLower(s)
	}
	if i == 1 {
		return strings.ToLower(s[:1]) + s[1:]
	}
	return strings.ToLower(s[:i-1]) + s[i-1:]
}
