// Copyright 2025 Redpanda Data, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: redpanda/runtime/v1alpha1/agent.proto

package runtimepb

import (
	runtimepb "github.com/redpanda-data/connect/v4/internal/rpcplugin/runtimepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TraceContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        string                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	TraceFlags    string                 `protobuf:"bytes,4,opt,name=trace_flags,json=traceFlags,proto3" json:"trace_flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceContext) Reset() {
	*x = TraceContext{}
	mi := &file_redpanda_runtime_v1alpha1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceContext) ProtoMessage() {}

func (x *TraceContext) ProtoReflect() protoreflect.Message {
	mi := &file_redpanda_runtime_v1alpha1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceContext.ProtoReflect.Descriptor instead.
func (*TraceContext) Descriptor() ([]byte, []int) {
	return file_redpanda_runtime_v1alpha1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *TraceContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TraceContext) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *TraceContext) GetTraceFlags() string {
	if x != nil {
		return x.TraceFlags
	}
	return ""
}

type Trace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spans         []*Span                `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trace) Reset() {
	*x = Trace{}
	mi := &file_redpanda_runtime_v1alpha1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trace) ProtoMessage() {}

func (x *Trace) ProtoReflect() protoreflect.Message {
	mi := &file_redpanda_runtime_v1alpha1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trace.ProtoReflect.Descriptor instead.
func (*Trace) Descriptor() ([]byte, []int) {
	return file_redpanda_runtime_v1alpha1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Trace) GetSpans() []*Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

type Span struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	SpanId        string                      `protobuf:"bytes,1,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	Name          string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartTime     *timestamppb.Timestamp      `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp      `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Attributes    map[string]*runtimepb.Value `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ChildSpans    []*Span                     `protobuf:"bytes,6,rep,name=child_spans,json=childSpans,proto3" json:"child_spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_redpanda_runtime_v1alpha1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_redpanda_runtime_v1alpha1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_redpanda_runtime_v1alpha1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Span) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Span) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Span) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Span) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Span) GetAttributes() map[string]*runtimepb.Value {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Span) GetChildSpans() []*Span {
	if x != nil {
		return x.ChildSpans
	}
	return nil
}

// InvokeAgentRequest is the request message for the `InvokeAgent` method.
type InvokeAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *runtimepb.Message     `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TraceContext  *TraceContext          `protobuf:"bytes,2,opt,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeAgentRequest) Reset() {
	*x = InvokeAgentRequest{}
	mi := &file_redpanda_runtime_v1alpha1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeAgentRequest) ProtoMessage() {}

func (x *InvokeAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redpanda_runtime_v1alpha1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeAgentRequest.ProtoReflect.Descriptor instead.
func (*InvokeAgentRequest) Descriptor() ([]byte, []int) {
	return file_redpanda_runtime_v1alpha1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *InvokeAgentRequest) GetMessage() *runtimepb.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *InvokeAgentRequest) GetTraceContext() *TraceContext {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

// InvokeAgentResponse is the response message for the `InvokeAgent` method.
type InvokeAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *runtimepb.Message     `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Trace         *Trace                 `protobuf:"bytes,2,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeAgentResponse) Reset() {
	*x = InvokeAgentResponse{}
	mi := &file_redpanda_runtime_v1alpha1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeAgentResponse) ProtoMessage() {}

func (x *InvokeAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redpanda_runtime_v1alpha1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeAgentResponse.ProtoReflect.Descriptor instead.
func (*InvokeAgentResponse) Descriptor() ([]byte, []int) {
	return file_redpanda_runtime_v1alpha1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *InvokeAgentResponse) GetMessage() *runtimepb.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *InvokeAgentResponse) GetTrace() *Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

var File_redpanda_runtime_v1alpha1_agent_proto protoreflect.FileDescriptor

const file_redpanda_runtime_v1alpha1_agent_proto_rawDesc = "" +
	"\n" +
	"%redpanda/runtime/v1alpha1/agent.proto\x12\x19redpanda.runtime.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a'redpanda/runtime/v1alpha1/message.proto\"c\n" +
	"\fTraceContext\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12\x1f\n" +
	"\vtrace_flags\x18\x04 \x01(\tR\n" +
	"traceFlags\">\n" +
	"\x05Trace\x125\n" +
	"\x05spans\x18\x01 \x03(\v2\x1f.redpanda.runtime.v1alpha1.SpanR\x05spans\"\x99\x03\n" +
	"\x04Span\x12\x17\n" +
	"\aspan_id\x18\x01 \x01(\tR\x06spanId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12O\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2/.redpanda.runtime.v1alpha1.Span.AttributesEntryR\n" +
	"attributes\x12@\n" +
	"\vchild_spans\x18\x06 \x03(\v2\x1f.redpanda.runtime.v1alpha1.SpanR\n" +
	"childSpans\x1a_\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .redpanda.runtime.v1alpha1.ValueR\x05value:\x028\x01\"\xa0\x01\n" +
	"\x12InvokeAgentRequest\x12<\n" +
	"\amessage\x18\x01 \x01(\v2\".redpanda.runtime.v1alpha1.MessageR\amessage\x12L\n" +
	"\rtrace_context\x18\x02 \x01(\v2'.redpanda.runtime.v1alpha1.TraceContextR\ftraceContext\"\x8b\x01\n" +
	"\x13InvokeAgentResponse\x12<\n" +
	"\amessage\x18\x01 \x01(\v2\".redpanda.runtime.v1alpha1.MessageR\amessage\x126\n" +
	"\x05trace\x18\x02 \x01(\v2 .redpanda.runtime.v1alpha1.TraceR\x05trace2|\n" +
	"\fAgentRuntime\x12l\n" +
	"\vInvokeAgent\x12-.redpanda.runtime.v1alpha1.InvokeAgentRequest\x1a..redpanda.runtime.v1alpha1.InvokeAgentResponseB>Z<github.com/redpanda-data/connect/v4/internal/agent/runtimepbb\x06proto3"

var (
	file_redpanda_runtime_v1alpha1_agent_proto_rawDescOnce sync.Once
	file_redpanda_runtime_v1alpha1_agent_proto_rawDescData []byte
)

func file_redpanda_runtime_v1alpha1_agent_proto_rawDescGZIP() []byte {
	file_redpanda_runtime_v1alpha1_agent_proto_rawDescOnce.Do(func() {
		file_redpanda_runtime_v1alpha1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_redpanda_runtime_v1alpha1_agent_proto_rawDesc), len(file_redpanda_runtime_v1alpha1_agent_proto_rawDesc)))
	})
	return file_redpanda_runtime_v1alpha1_agent_proto_rawDescData
}

var file_redpanda_runtime_v1alpha1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_redpanda_runtime_v1alpha1_agent_proto_goTypes = []any{
	(*TraceContext)(nil),          // 0: redpanda.runtime.v1alpha1.TraceContext
	(*Trace)(nil),                 // 1: redpanda.runtime.v1alpha1.Trace
	(*Span)(nil),                  // 2: redpanda.runtime.v1alpha1.Span
	(*InvokeAgentRequest)(nil),    // 3: redpanda.runtime.v1alpha1.InvokeAgentRequest
	(*InvokeAgentResponse)(nil),   // 4: redpanda.runtime.v1alpha1.InvokeAgentResponse
	nil,                           // 5: redpanda.runtime.v1alpha1.Span.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*runtimepb.Message)(nil),     // 7: redpanda.runtime.v1alpha1.Message
	(*runtimepb.Value)(nil),       // 8: redpanda.runtime.v1alpha1.Value
}
var file_redpanda_runtime_v1alpha1_agent_proto_depIdxs = []int32{
	2,  // 0: redpanda.runtime.v1alpha1.Trace.spans:type_name -> redpanda.runtime.v1alpha1.Span
	6,  // 1: redpanda.runtime.v1alpha1.Span.start_time:type_name -> google.protobuf.Timestamp
	6,  // 2: redpanda.runtime.v1alpha1.Span.end_time:type_name -> google.protobuf.Timestamp
	5,  // 3: redpanda.runtime.v1alpha1.Span.attributes:type_name -> redpanda.runtime.v1alpha1.Span.AttributesEntry
	2,  // 4: redpanda.runtime.v1alpha1.Span.child_spans:type_name -> redpanda.runtime.v1alpha1.Span
	7,  // 5: redpanda.runtime.v1alpha1.InvokeAgentRequest.message:type_name -> redpanda.runtime.v1alpha1.Message
	0,  // 6: redpanda.runtime.v1alpha1.InvokeAgentRequest.trace_context:type_name -> redpanda.runtime.v1alpha1.TraceContext
	7,  // 7: redpanda.runtime.v1alpha1.InvokeAgentResponse.message:type_name -> redpanda.runtime.v1alpha1.Message
	1,  // 8: redpanda.runtime.v1alpha1.InvokeAgentResponse.trace:type_name -> redpanda.runtime.v1alpha1.Trace
	8,  // 9: redpanda.runtime.v1alpha1.Span.AttributesEntry.value:type_name -> redpanda.runtime.v1alpha1.Value
	3,  // 10: redpanda.runtime.v1alpha1.AgentRuntime.InvokeAgent:input_type -> redpanda.runtime.v1alpha1.InvokeAgentRequest
	4,  // 11: redpanda.runtime.v1alpha1.AgentRuntime.InvokeAgent:output_type -> redpanda.runtime.v1alpha1.InvokeAgentResponse
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_redpanda_runtime_v1alpha1_agent_proto_init() }
func file_redpanda_runtime_v1alpha1_agent_proto_init() {
	if File_redpanda_runtime_v1alpha1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_redpanda_runtime_v1alpha1_agent_proto_rawDesc), len(file_redpanda_runtime_v1alpha1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_redpanda_runtime_v1alpha1_agent_proto_goTypes,
		DependencyIndexes: file_redpanda_runtime_v1alpha1_agent_proto_depIdxs,
		MessageInfos:      file_redpanda_runtime_v1alpha1_agent_proto_msgTypes,
	}.Build()
	File_redpanda_runtime_v1alpha1_agent_proto = out.File
	file_redpanda_runtime_v1alpha1_agent_proto_goTypes = nil
	file_redpanda_runtime_v1alpha1_agent_proto_depIdxs = nil
}
