name: Release Auto Tag

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  tag:
    if: github.event.pull_request.merged && startsWith(github.event.pull_request.head.ref, 'changelog/v')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ vars.RP_AWS_CRED_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.RP_AWS_CRED_ACCOUNT_ID }}:role/${{ vars.RP_AWS_CRED_BASE_ROLE_NAME }}${{ github.event.repository.name }}

      - name: Get secrets from AWS Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,sdlc/prod/github/actions_bot_token
          parse-json-secrets: true

      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ env.ACTIONS_BOT_TOKEN }}

      - name: Create tag
        env:
          TAG: ${{ github.event.pull_request.head.ref }}
        run: |
          TAG="${TAG#changelog/}"
          if git ls-remote --tags origin "refs/tags/$TAG" | grep -q .; then
            echo "Tag $TAG already exists, skipping"
            exit 0
          fi
          git tag "$TAG"
          git push origin "$TAG"
